function record=sc01b_validate_native_record(r,storedParameters,expected,row,criteria)
%SC01B_VALIDATE_NATIVE_RECORD Check declared native settings and actual grid.
% Pure record validation: no simulation, file changes, or source backstamping.
% Source sidecars are checked by the collector before this helper is called.
tag=string(row.Run);
tags=compose("native_%g_ns",criteria.nativeSteps_s*1e9);
settings=expected.simulation;
if tag=="native_tight_consistency"
    assert(ismember(string(row.Case),criteria.consistencyCases), ...
        'SC01B:WorkerNativeTag','Tight consistency is not declared for this case.');
    settings.maxStep_s=criteria.nativeSteps_s(end);
    settings.consistencyAbsoluteTolerance=1e-13;
    settings.consistencyRelativeTolerance=1e-9;
else
    index=find(tags==tag);
    assert(isscalar(index),'SC01B:WorkerNativeTag','Unknown or ambiguous native run tag: %s',tag);
    settings.maxStep_s=criteria.nativeSteps_s(index);
end
settings=sc01b_local_solver_settings(settings);
assert(string(row.Case)==string(expected.meta.case) && ...
    isequaln(storedParameters,expected) && isfield(r,'params') && isequaln(r.params,expected), ...
    'SC01B:WorkerNativeParameters','Native parameters disagree with the declared case.');
assert(isfield(r,'settings') && isequaln(r.settings,settings) && ...
    isfinite(row.Step_s) && abs(row.Step_s-settings.maxStep_s)<=1e-20, ...
    'SC01B:WorkerNativeSettings','Native solver settings disagree with run tag %s.',tag);
assert(isfield(r,'time_s') && isnumeric(r.time_s) && isreal(r.time_s) && ...
    iscolumn(r.time_s) && numel(r.time_s)>=2 && all(isfinite(r.time_s)) && ...
    all(diff(r.time_s)>0), ...
    'SC01B:WorkerNativeGrid','Native time must be a finite strictly increasing column.');
step=settings.maxStep_s;stop=settings.stopTime_s;
intervalCount=round(stop/step);
gridTolerance=max(2e-20,16*eps(max(abs(r.time_s(end)),abs(stop))));
assert(abs(intervalCount*step-stop)<=gridTolerance, ...
    'SC01B:WorkerNativeGrid','Declared native stop time is not on its fixed-step grid.');
expectedTime=(0:intervalCount)'*step;
assert(isequal(size(r.time_s),size(expectedTime)) && ...
    max(abs(r.time_s-expectedTime))<=gridTolerance && ...
    max(abs(diff(r.time_s)-step))<=gridTolerance, ...
    'SC01B:WorkerNativeGrid','Actual native integration grid disagrees with the declared fixed step.');
stopEvent="";
% MATLAB metadata may be an object or a structure in loaded records.
try
    stopEvent=string(r.executionInfo.StopEvent);
catch
    % Missing/unreadable completion evidence is rejected below.
end
assert(isfield(r,'warningCount') && r.warningCount==0 && row.Warnings==0 && ...
    row.Completed && isfinite(row.Samples) && row.Samples==numel(r.time_s) && ...
    isfinite(row.StopTime_s) && abs(row.StopTime_s-stop)<=gridTolerance && ...
    stopEvent=="ReachedStopTime", ...
    'SC01B:WorkerNativeRecord','Native completion facts disagree with the run manifest.');
record=struct('case',string(row.Case),'run',tag,'completeSettingsMatched',true, ...
    'uniformIntegrationGridPassed',true,'samples',numel(r.time_s), ...
    'observedMaxStep_s',max(diff(r.time_s)),'gridTolerance_s',gridTolerance);
end
