function write_sc01a_summary(study,outputFolder)
%WRITE_SC01A_SUMMARY Generate an evidence-based circuit validation report.
arguments
    study (1,1) struct
    outputFolder (1,1) string
end
fid=fopen(fullfile(outputFolder,'SC01A_Validation_Summary.md'),'w','n','UTF-8');
assert(fid>=0,'SC01A:CannotWriteSummary','Cannot open summary file.');
cleanup=onCleanup(@()fclose(fid));
fine=study.metrics(study.metrics.Level==3,:);
fprintf(fid,'# SC-01A Finite-Edge Circuit Validation\n\n');
fprintf(fid,'Run: %s. MATLAB %s. Parameter set: `%s`.\n\n', ...
    study.meta.createdUTC,study.meta.matlabVersion,study.meta.parameterId);
fprintf(fid,['**SC-01A is implemented and numerically verified.** The native Simscape model resolves prescribed ', ...
    'finite switching edges through an explicit two-line receiver circuit and a loaded shared return. ', ...
    'The model, source data, raw refined traces, threshold records, solver-refinement evidence and repeatable ', ...
    'workflow are saved. This is circuit-model verification with assumed inputs; no hardware measurements ', ...
    'or transistor switching-source validation are claimed.\n\n']);
fprintf(fid,'## What was built\n\n');
fprintf(fid,['- Two explicit aggressor-to-line coupling capacitors (10/9 pF nominal).\n', ...
    '- Behavioral series induced-voltage sources from 20/17 nH times prescribed commutation-current slope. These are not a reciprocal mutual-inductor device model.\n', ...
    '- A physical 25 milliohm / 20 nH shared return carrying actual return current, including receiver/driver loading.\n', ...
    '- A 120 ohm / 100 pF differential receiver load, 47/53 ohm source resistances, 50/70 pF line-to-ground capacitances, and 10/20 kilohm bias returns.\n', ...
    '- Intended open-circuit differential source levels of +2 or -2 V at 2.5 V common mode, with finite victim transitions. The loaded nominal high differential is approximately 1.085917 V.\n', ...
    '- Actual conserving-port voltage/current sensors and an independent three-state, piecewise-exact affine circuit reference.\n\n']);
fprintf(fid,['All new circuit values remain declared assumptions. The old scalar path-transfer factors, common-mode conversion factors ', ...
    'and volts-to-radians mapping are not applied to this circuit. The 24 V / 100 ns and 3 A / 200 ns ', ...
    'ramps are independent bench excitations. Negative-edge tests use signed perturbations from zero ', ...
    'to -24 V / -3 A; they are not selected-device turn-off waveforms.\n\n']);
fprintf(fid,'## Verification results\n\n');
fprintf(fid,'| Check | Result |\n|---|---:|\n');
fprintf(fid,'| Existing + new automated tests | %d / %d passed |\n',nnz(study.tests.Passed),height(study.tests));
fprintf(fid,'| Deterministic circuit cases | %d |\n',height(fine));
fprintf(fid,'| Native circuit simulations | %d |\n',study.meta.nativeRuns);
fprintf(fid,'| Native simulation warnings | %d (all runs reached stop time) |\n', ...
    sum(study.metrics.WarningCount)+sum(study.tolerance.WarningCount));
fprintf(fid,'| Step refinements, 1 to 0.5 to 0.25 ns | %d / %d passed |\n',nnz(study.convergence.Passed),height(study.convergence));
fprintf(fid,'| Tenfold tolerance refinements | %d / %d passed |\n',nnz(study.tolerance.Passed),height(study.tolerance));
fprintf(fid,'| Native symmetry, zero-input and superposition checks | %d / %d passed |\n',nnz(study.nativeInvariants.Passed),height(study.nativeInvariants));
if isfield(study,'periodComparison')
    fprintf(fid,'| Last-period waveform/state comparisons, 10 versus 20 PWM periods | %d / %d passed |\n', ...
        nnz(study.periodComparison.Passed),height(study.periodComparison));
end
fprintf(fid,'| Largest refined differential reference error | %.6g V |\n',max(fine.ReferenceDMError_V));
fprintf(fid,'| Largest refined common-mode reference error | %.6g V |\n',max(fine.ReferenceCMError_V));
fprintf(fid,'| Largest refined ground reference error, away from exact source corners | %.6g V |\n',max(fine.ReferenceGroundError_V));
fprintf(fid,'| Largest refined return-current reference error | %.6g A |\n\n',max(fine.ReferenceCurrentError_A));
fprintf(fid,['The native variable-step solver is `ode23t`, with local fixed-step solving and input filtering disabled. ', ...
    'Explicit duplicate-time left/right values mark rectangular induced-voltage and derivative-source discontinuities ', ...
    'without smoothing them. An early pilot with zero-order-held jumps produced minimum-step warnings; ', ...
    'the explicit event encoding corrected that issue before the final campaign. ', ...
    'The final campaign records zero simulation warnings and completed stop times for every recorded run. ', ...
    'The adapter retains engine diagnostics and rejects any warning; an intentionally injected warning ', ...
    'was also checked to confirm that this rejection path works.\n\n']);
fprintf(fid,['Every standard case uses maximum integration steps of 1, 0.5 and 0.25 ns with relative tolerance 1e-5 ', ...
    'and absolute tolerance 1e-9. Three representative cases repeat 0.25 ns with tolerances 1e-6 and 1e-10. ', ...
    'These are actual integration settings, not just exported sample spacing. All outputs are finite and ', ...
    'the loaded DC initialization is checked independently. Short-record reference checks use every native solver point; ', ...
    'long records use 100,001 selected native points plus source-corner neighborhoods. Exact algebraic source-corner ', ...
    'timestamps are excluded only from pointwise ground-voltage comparison because left/right values differ. ', ...
    'State voltages and return current remain checked at every selected point.\n\n']);

fprintf(fid,'## Refined circuit results\n\n');
fprintf(fid,['Differential and common-mode disturbances subtract the matching intended-only loaded-circuit response. ', ...
    'The threshold columns use the **total** differential receiver input; +/-0.20 V is an illustrative ', ...
    'diagnostic band, not a selected receiver model.\n\n']);
fprintf(fid,'| Case | Peak differential disturbance (mV) | Peak common-mode disturbance (mV) | Total input minimum (V) | Time inside +/-0.20 V band (ns) |\n|---|---:|---:|---:|---:|\n');
for k=1:height(fine)
    fprintf(fid,'| `%s` | %.5f | %.5f | %.6f | %.5f |\n',fine.Case(k), ...
        fine.PeakDM_V(k)*1e3,fine.PeakCM_V(k)*1e3,fine.MinimumTotalDifferential_V(k),fine.ReceiverBand_s(k)*1e9);
end
fprintf(fid,['\n`stress_fall` increases the positive-line aggressor capacitance to 300 pF and reduces the negative-line ', ...
    'value to 5 pF while applying a negative bench edge. These are exploratory stress settings, not measurements. ', ...
    'The transition cases deliberately change the intended signal; their diagnostic-band residence is partly ', ...
    'an intended transition and is not counted as a receiver failure. Event CSVs record level, direction, time ', ...
    'and whether the crossing belongs to noise delta or total receiver input.\n\n']);

fprintf(fid,'## Numerical acceptance and what it establishes\n\n');
fprintf(fid,['Successive peak changes must stay below the larger of 1%% of the refined disturbance peak or 0.1 mV. ', ...
    'Absolute integrated-disturbance changes use the larger of 1%% of the refined area or ', ...
    '0.1 mV times the 100 ns source-ramp duration (1e-11 V*s). Matched crossing-time and exposure-duration ', ...
    'changes must be below 1 ns, with identical crossing classifications. Near-threshold extrema or plateaus ', ...
    'are flagged as grazing and cannot silently pass. The complete ratios and differences are in the convergence tables.\n\n']);
fprintf(fid,['The original passive network is held fixed for source-decomposition superposition. Zero coupling is ', ...
    'a separate topology test: zero-valued coupling capacitors are physically omitted. The balanced case removes ', ...
    'all paired-line asymmetries, not only capacitor or mutual-term imbalance. ', ...
    'For PWM settling, corresponding final complete periods are compared at a common time grid; twice-longer total areas ', ...
    'are not mistaken for a settling comparison.\n\n']);
fprintf(fid,['These results verify the deterministic circuit implementation and numerical resolution. They do not predict ', ...
    'a real receiver output glitch, an encoder count error, a communication error rate, an EMC limit or ', ...
    'robot stability under measured interference. The model still omits selected-device switching charge, ', ...
    'a reciprocal multi-conductor inductance network, nonlinear input clamps, distributed cable propagation ', ...
    'and a complete receiver/decoder.\n\n']);

fprintf(fid,'## Files and rerun\n\n');
fprintf(fid,['From `06_Circuit_Simulations/SC01A`, run `sc01a_main`. The workflow runs the current control/sensitivity ', ...
    'and circuit/threshold tests, the native case matrix, refinement checks, figures and this report in a fresh timestamped workflow folder. ', ...
    'This report and circuit artifacts are in its `campaign` child folder; test results are one directory above. ', ...
    'The saved `models/EMI_SC01A_Finite_Edge.slx` includes nominal default inputs and parameters for standalone Run.\n\n', ...
    '- `models/EMI_SC01A_Finite_Edge.slx` and its PNG diagram: actual native conserving circuit.\n', ...
    '- `sc01a_parameters.json`: parameter set and assumed provenance.\n', ...
    '- `sc01a_case_manifest.json` and CSV: complete case parameters and a compact case-input table.\n', ...
    '- `sc01a_case_metrics.csv`: solver settings, metrics, reference errors, sample counts and runtimes.\n', ...
    '- `sc01a_convergence.csv`, `sc01a_tolerance_refinement.csv`, `sc01a_native_invariants.csv`, `sc01a_period_settling.csv`: numerical checks.\n', ...
    '- `../sc01a_tests.csv`: automated workflow test evidence.\n', ...
    '- `sc01a_*_events.csv`: interpolated threshold-crossing records.\n', ...
    '- `sc01a_*_timeseries.csv`: full refined short-case traces; `sc01a_pwm_*_last_period.csv`: last-period views.\n', ...
    '- `raw/sc01a_*.mat`: full native refined traces and complete case/source definitions, including long PWM runs.\n', ...
    '- `sc01a_study.mat`: campaign metrics, comparisons and representative examples.\n', ...
    '- `sc01a_overview.png`: checked result overview.\n', ...
    '- `sc01a_refinement_overlay.png` and `sc01a_combined_rise_refinement_*_ns.csv`: three retained native-grid waveform refinements.\n\n']);
fprintf(fid,'## Next work\n\n');
fprintf(fid,['SC-01A is complete. SC-01B will replace the prescribed sources with a device-parameterized half-bridge ', ...
    'after driver, MOSFET/diode, charge/capacitance and commutation-loop data are selected and recorded. ', ...
    'Receiver/decoder identification and measured circuit comparison remain necessary for physical validation. ', ...
    'Supply interruption and Phase 3 resilient control remain separate unfinished project work.\n']);
end
