classdef TestPhase2B < matlab.unittest.TestCase
    %TESTPHASE2B Verify reduced-order coupling and communication faults.

    properties
        Params
        Time_s
        Phase2ANone
        Phase2BNone
        Phase2BCombined
    end

    methods (TestClassSetup)
        function createMatchedReferences(testCase)
            testCase.Params = actuator_parameters();
            testCase.Time_s = (0:testCase.Params.control.sampleTime_s: ...
                testCase.Params.simulation.stopTime_s).';

            phase2aScenario = encoder_fault_scenario("none", testCase.Params);
            phase2bScenario = phase2b_scenario("none", testCase.Params);
            combinedScenario = phase2b_scenario( ...
                "combined_phase2b", testCase.Params);

            testCase.Phase2ANone = simulate_faulted_actuator( ...
                testCase.Params, phase2aScenario);
            testCase.Phase2BNone = simulate_phase2b_actuator( ...
                testCase.Params, phase2bScenario);
            testCase.Phase2BCombined = simulate_phase2b_actuator( ...
                testCase.Params, combinedScenario);
        end
    end

    methods (Test)
        function noFaultRegressesToPhase2A(testCase)
            phase2a = testCase.Phase2ANone.timeSeries;
            phase2b = testCase.Phase2BNone;

            testCase.verifyEqual(phase2b.position_rad, ...
                phase2a.theta_rad, 'AbsTol', 1e-12);
            testCase.verifyEqual(phase2b.sensorSideMeasurement_rad, ...
                phase2a.theta_measured_rad, 'AbsTol', 1e-12);
            testCase.verifyEqual(phase2b.receivedMeasurement_rad, ...
                phase2a.theta_measured_rad, 'AbsTol', 1e-12);
            testCase.verifyEqual(phase2b.trackingError_rad, ...
                phase2a.theta_ref_rad - phase2a.theta_measured_rad, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(phase2b.command_V, ...
                phase2a.voltage_cmd_V, 'AbsTol', 1e-12);
            testCase.verifyFalse(any( ...
                phase2b.profile.configuredWindowActive));
        end

        function configuredWindowsAreHalfOpen(testCase)
            params = testCase.Params;
            time_s = testCase.Time_s;
            scenario = phase2b_scenario("combined_phase2b", params);
            physical = physical_coupling_profile(time_s, params, scenario);
            channel = communication_channel_profile(time_s, params, scenario);

            expectedSource = time_s >= params.phase2b.source.startTime_s & ...
                time_s < params.phase2b.source.stopTime_s;
            expectedGround = time_s >= ...
                params.phase2b.groundOffset.startTime_s & ...
                time_s < params.phase2b.groundOffset.stopTime_s;
            expectedChannel = time_s >= ...
                params.phase2b.communication.startTime_s & ...
                time_s < params.phase2b.communication.stopTime_s;

            testCase.verifyEqual(physical.sourceWindowActive, expectedSource);
            testCase.verifyEqual(physical.groundWindowActive, expectedGround);
            testCase.verifyEqual(channel.configuredWindowActive, ...
                expectedChannel);
            testCase.verifyEqual(nnz(expectedSource), round( ...
                (params.phase2b.source.stopTime_s - ...
                params.phase2b.source.startTime_s) / ...
                params.control.sampleTime_s));
            testCase.verifyEqual(nnz(expectedGround), round( ...
                (params.phase2b.groundOffset.stopTime_s - ...
                params.phase2b.groundOffset.startTime_s) / ...
                params.control.sampleTime_s));
            testCase.verifyEqual(nnz(expectedChannel), round( ...
                (params.phase2b.communication.stopTime_s - ...
                params.phase2b.communication.startTime_s) / ...
                params.control.sampleTime_s));

            sourceStopIndex = round( ...
                params.phase2b.source.stopTime_s / ...
                params.control.sampleTime_s) + 1;
            groundStopIndex = round( ...
                params.phase2b.groundOffset.stopTime_s / ...
                params.control.sampleTime_s) + 1;
            channelStopIndex = round( ...
                params.phase2b.communication.stopTime_s / ...
                params.control.sampleTime_s) + 1;
            testCase.verifyFalse(physical.sourceWindowActive(sourceStopIndex));
            testCase.verifyFalse(physical.groundWindowActive(groundStopIndex));
            testCase.verifyFalse(channel.configuredWindowActive( ...
                channelStopIndex));
        end

        function physicalPeakEquationsAreCorrect(testCase)
            params = testCase.Params;
            scenario = phase2b_scenario("combined_coupling", params);
            profile = physical_coupling_profile( ...
                testCase.Time_s, params, scenario);
            p = params.phase2b;

            dvdt = p.source.switchingVoltageStep_V / ...
                p.source.voltageRiseTime_s;
            didt = p.source.currentStep_A / ...
                p.source.currentRiseTime_s;
            deltaC = p.coupling.capacitive.linePositive_F - ...
                p.coupling.capacitive.lineNegative_F;
            deltaM = p.coupling.inductive.linePositive_H - ...
                p.coupling.inductive.lineNegative_H;
            receiverGain = 1 / sqrt(1 + ...
                (p.source.observedBasebandFrequency_Hz / ...
                p.receiver.bandwidth_Hz)^2);
            expectedCapCurrent = deltaC * dvdt;
            expectedCapVoltage = ...
                p.coupling.capacitive.pathTransferLinear * ...
                p.receiver.differentialTermination_Ohm * ...
                expectedCapCurrent * receiverGain;
            expectedIndVoltage = ...
                p.coupling.inductive.pathTransferLinear * ...
                deltaM * didt * receiverGain;
            expectedSharedReturn = ...
                p.coupling.shared.returnResistance_Ohm * ...
                p.source.currentStep_A + ...
                p.coupling.shared.returnInductance_H * didt;
            expectedSharedDifferential = ...
                p.coupling.shared.commonModeToDifferential * ...
                expectedSharedReturn * receiverGain;

            testCase.verifyEqual(profile.derived.dvdt_V_s, dvdt, ...
                'RelTol', 1e-14);
            testCase.verifyEqual(profile.derived.didt_A_s, didt, ...
                'RelTol', 1e-14);
            testCase.verifyEqual( ...
                profile.derived.capacitiveCurrentPeak_A, ...
                expectedCapCurrent, 'RelTol', 1e-14);
            testCase.verifyEqual( ...
                profile.derived.capacitiveVoltagePeak_V, ...
                expectedCapVoltage, 'RelTol', 1e-14);
            testCase.verifyEqual( ...
                profile.derived.inductiveVoltagePeak_V, ...
                expectedIndVoltage, 'RelTol', 1e-14);
            testCase.verifyEqual( ...
                profile.derived.sharedReturnVoltagePeak_V, ...
                expectedSharedReturn, 'RelTol', 1e-14);
            testCase.verifyEqual( ...
                profile.derived.sharedDifferentialVoltagePeak_V, ...
                expectedSharedDifferential, 'RelTol', 1e-14);
        end

        function physicalModelsScaleLinearly(testCase)
            params = testCase.Params;

            capScenario = phase2b_scenario("capacitive_coupling", params);
            capBase = physical_coupling_profile( ...
                testCase.Time_s, params, capScenario);
            capScaledParams = params;
            originalDeltaC = ...
                params.phase2b.coupling.capacitive.linePositive_F - ...
                params.phase2b.coupling.capacitive.lineNegative_F;
            capScaledParams.phase2b.coupling.capacitive.linePositive_F = ...
                params.phase2b.coupling.capacitive.lineNegative_F + ...
                2 * originalDeltaC;
            capScaled = physical_coupling_profile( ...
                testCase.Time_s, capScaledParams, capScenario);
            testCase.verifyEqual(capScaled.capacitiveVoltage_V, ...
                2 * capBase.capacitiveVoltage_V, 'AbsTol', 1e-14);

            indScenario = phase2b_scenario("inductive_coupling", params);
            indBase = physical_coupling_profile( ...
                testCase.Time_s, params, indScenario);
            indScaledParams = params;
            originalDeltaM = ...
                params.phase2b.coupling.inductive.linePositive_H - ...
                params.phase2b.coupling.inductive.lineNegative_H;
            indScaledParams.phase2b.coupling.inductive.linePositive_H = ...
                params.phase2b.coupling.inductive.lineNegative_H + ...
                2 * originalDeltaM;
            indScaled = physical_coupling_profile( ...
                testCase.Time_s, indScaledParams, indScenario);
            testCase.verifyEqual(indScaled.inductiveVoltage_V, ...
                2 * indBase.inductiveVoltage_V, 'AbsTol', 1e-14);

            sharedScenario = phase2b_scenario("shared_impedance", params);
            sharedBase = physical_coupling_profile( ...
                testCase.Time_s, params, sharedScenario);
            sharedScaledParams = params;
            sharedScaledParams.phase2b.coupling.shared.returnResistance_Ohm = ...
                2 * params.phase2b.coupling.shared.returnResistance_Ohm;
            sharedScaledParams.phase2b.coupling.shared.returnInductance_H = ...
                2 * params.phase2b.coupling.shared.returnInductance_H;
            sharedScaled = physical_coupling_profile( ...
                testCase.Time_s, sharedScaledParams, sharedScenario);
            testCase.verifyEqual(sharedScaled.sharedImpedanceVoltage_V, ...
                2 * sharedBase.sharedImpedanceVoltage_V, 'AbsTol', 1e-14);
        end

        function differentialImbalanceControlsPolarity(testCase)
            params = testCase.Params;

            capScenario = phase2b_scenario("capacitive_coupling", params);
            capBase = physical_coupling_profile( ...
                testCase.Time_s, params, capScenario);
            capReversedParams = params;
            capReversedParams.phase2b.coupling.capacitive.linePositive_F = ...
                params.phase2b.coupling.capacitive.lineNegative_F;
            capReversedParams.phase2b.coupling.capacitive.lineNegative_F = ...
                params.phase2b.coupling.capacitive.linePositive_F;
            capReversed = physical_coupling_profile( ...
                testCase.Time_s, capReversedParams, capScenario);
            testCase.verifyEqual(capReversed.capacitiveVoltage_V, ...
                -capBase.capacitiveVoltage_V, 'AbsTol', 1e-14);

            indScenario = phase2b_scenario("inductive_coupling", params);
            indBase = physical_coupling_profile( ...
                testCase.Time_s, params, indScenario);
            indReversedParams = params;
            indReversedParams.phase2b.coupling.inductive.linePositive_H = ...
                params.phase2b.coupling.inductive.lineNegative_H;
            indReversedParams.phase2b.coupling.inductive.lineNegative_H = ...
                params.phase2b.coupling.inductive.linePositive_H;
            indReversed = physical_coupling_profile( ...
                testCase.Time_s, indReversedParams, indScenario);
            testCase.verifyEqual(indReversed.inductiveVoltage_V, ...
                -indBase.inductiveVoltage_V, 'AbsTol', 1e-14);
        end

        function isolatedScenariosActivateOnlyTheirMechanism(testCase)
            params = testCase.Params;
            time_s = testCase.Time_s;

            cap = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("capacitive_coupling", params));
            testCase.verifyGreaterThan(nnz(cap.capacitiveVoltage_V), 0);
            testCase.verifyEqual(cap.inductiveVoltage_V, zeros(size(time_s)));
            testCase.verifyEqual(cap.sharedImpedanceVoltage_V, ...
                zeros(size(time_s)));
            testCase.verifyEqual(cap.groundDifferentialVoltage_V, ...
                zeros(size(time_s)));

            ind = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("inductive_coupling", params));
            testCase.verifyEqual(ind.capacitiveVoltage_V, zeros(size(time_s)));
            testCase.verifyGreaterThan(nnz(ind.inductiveVoltage_V), 0);
            testCase.verifyEqual(ind.sharedImpedanceVoltage_V, ...
                zeros(size(time_s)));

            shared = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("shared_impedance", params));
            testCase.verifyEqual(shared.capacitiveVoltage_V, ...
                zeros(size(time_s)));
            testCase.verifyEqual(shared.inductiveVoltage_V, zeros(size(time_s)));
            testCase.verifyGreaterThan(nnz(shared.sharedImpedanceVoltage_V), 0);

            ground = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("ground_offset", params));
            testCase.verifyGreaterThan(nnz( ...
                ground.groundDifferentialVoltage_V), 0);
            testCase.verifyEqual(ground.capacitiveVoltage_V, zeros(size(time_s)));
            testCase.verifyEqual(ground.inductiveVoltage_V, zeros(size(time_s)));
            testCase.verifyEqual(ground.sharedImpedanceVoltage_V, ...
                zeros(size(time_s)));
        end

        function couplingSuperpositionIsExact(testCase)
            params = testCase.Params;
            time_s = testCase.Time_s;
            cap = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("capacitive_coupling", params));
            ind = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("inductive_coupling", params));
            shared = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("shared_impedance", params));
            ground = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("ground_offset", params));
            combined = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("combined_coupling", params));
            allMechanisms = physical_coupling_profile(time_s, params, ...
                phase2b_scenario("combined_phase2b", params));

            expectedCoupling = cap.receiverDifferentialVoltage_V + ...
                ind.receiverDifferentialVoltage_V + ...
                shared.receiverDifferentialVoltage_V;
            testCase.verifyEqual(combined.receiverDifferentialVoltage_V, ...
                expectedCoupling, 'AbsTol', 1e-14);
            testCase.verifyEqual( ...
                allMechanisms.receiverDifferentialVoltage_V, ...
                expectedCoupling + ground.receiverDifferentialVoltage_V, ...
                'AbsTol', 1e-14);
        end

        function zeroTransferCoefficientsRejectPhysicalCoupling(testCase)
            params = testCase.Params;
            params.phase2b.coupling.capacitive.pathTransferLinear = 0;
            params.phase2b.coupling.inductive.pathTransferLinear = 0;
            params.phase2b.coupling.shared.commonModeToDifferential = 0;
            params.phase2b.groundOffset.commonModeToDifferential = 0;
            scenario = phase2b_scenario("combined_phase2b", params);
            profile = physical_coupling_profile( ...
                testCase.Time_s, params, scenario);

            testCase.verifyEqual(profile.receiverDifferentialVoltage_V, ...
                zeros(size(testCase.Time_s)));
            testCase.verifyEqual(profile.equivalentEncoderError_rad, ...
                zeros(size(testCase.Time_s)));
            testCase.verifyFalse(any(profile.receiverMarginExceeded));
        end

        function communicationSchedulerIsDeterministic(testCase)
            params = testCase.Params;
            scenario = phase2b_scenario("combined_phase2b", params);

            rng(7401, "twister");
            expectedNextDraws = rand(5, 1);
            rng(7401, "twister");
            first = communication_channel_profile( ...
                testCase.Time_s, params, scenario);
            actualNextDraws = rand(5, 1);
            second = communication_channel_profile( ...
                testCase.Time_s, params, scenario);

            testCase.verifyEqual(first.transmitDelay_samples, ...
                second.transmitDelay_samples);
            testCase.verifyEqual(first.packetDropped, second.packetDropped);
            testCase.verifyEqual(first.arrivalIndex, second.arrivalIndex);
            testCase.verifyEqual(first.sampleReceived, second.sampleReceived);
            testCase.verifyEqual(first.acceptedSourceIndex, ...
                second.acceptedSourceIndex);
            testCase.verifyEqual(actualNextDraws, expectedNextDraws);
        end

        function acceptedPacketsAreCausalAndMonotonic(testCase)
            profile = testCase.Phase2BCombined.communication;
            arrivalSampleIndex = find(profile.sampleReceived);
            accepted = profile.acceptedSourceIndex(profile.sampleReceived);

            testCase.verifyLessThanOrEqual(accepted, arrivalSampleIndex);
            testCase.verifyGreaterThan(diff(accepted), 0);
            testCase.verifyGreaterThanOrEqual( ...
                diff(profile.lastAcceptedSourceIndex), 0);
            testCase.verifyEqual(profile.acceptedDelay_samples( ...
                profile.sampleReceived), arrivalSampleIndex - accepted);

            transmitted = profile.arrivalIndex > 0;
            sourceIndex = find(transmitted);
            testCase.verifyGreaterThanOrEqual( ...
                profile.arrivalIndex(transmitted), sourceIndex);
        end

        function fixedDelayAndJitterStayWithinBounds(testCase)
            params = testCase.Params;
            time_s = testCase.Time_s;
            active = time_s >= params.phase2b.communication.startTime_s & ...
                time_s < params.phase2b.communication.stopTime_s;

            fixed = communication_channel_profile(time_s, params, ...
                phase2b_scenario("communication_delay", params));
            testCase.verifyEqual(fixed.transmitDelay_samples(active), ...
                repmat(params.phase2b.communication.fixedDelay_samples, ...
                nnz(active), 1));
            testCase.verifyEqual(fixed.transmitDelay_samples(~active), ...
                zeros(nnz(~active), 1));

            jitter = communication_channel_profile(time_s, params, ...
                phase2b_scenario("communication_jitter", params));
            testCase.verifyGreaterThanOrEqual( ...
                jitter.transmitDelay_samples(active), 0);
            testCase.verifyLessThanOrEqual( ...
                jitter.transmitDelay_samples(active), ...
                params.phase2b.communication.maximumJitter_samples);
            testCase.verifyEqual(jitter.transmitDelay_samples(active), ...
                floor(jitter.transmitDelay_samples(active)));
            testCase.verifyEqual(jitter.transmitDelay_samples(~active), ...
                zeros(nnz(~active), 1));

            combined = testCase.Phase2BCombined.communication;
            testCase.verifyGreaterThanOrEqual( ...
                combined.transmitDelay_samples(active), ...
                params.phase2b.communication.fixedDelay_samples);
            testCase.verifyLessThanOrEqual( ...
                combined.transmitDelay_samples(active), ...
                params.phase2b.communication.fixedDelay_samples + ...
                params.phase2b.communication.maximumJitter_samples);
        end

        function packetLossProbabilityEndpointsAreExact(testCase)
            paramsZero = testCase.Params;
            paramsZero.phase2b.communication.packetLossProbability = 0;
            scenarioZero = phase2b_scenario("packet_loss", paramsZero);
            zeroProfile = communication_channel_profile( ...
                testCase.Time_s, paramsZero, scenarioZero);
            testCase.verifyFalse(any(zeroProfile.packetDropped));

            paramsOne = testCase.Params;
            paramsOne.phase2b.communication.packetLossProbability = 1;
            scenarioOne = phase2b_scenario("packet_loss", paramsOne);
            oneProfile = communication_channel_profile( ...
                testCase.Time_s, paramsOne, scenarioOne);
            active = oneProfile.channelEnabled;
            testCase.verifyEqual(oneProfile.packetDropped, active);
            testCase.verifyFalse(any(oneProfile.sampleReceived(active)));
            testCase.verifyTrue(all(oneProfile.heldLast(active)));

            resultOne = simulate_phase2b_actuator(paramsOne, scenarioOne);
            heldMeasurements = resultOne.receivedMeasurement_rad(active);
            testCase.verifyEqual(heldMeasurements, ...
                repmat(heldMeasurements(1), size(heldMeasurements)), ...
                'AbsTol', 1e-12);
        end

        function combinedFaultIsIdenticalBeforeOnset(testCase)
            scenario = testCase.Phase2BCombined.scenario;
            preOnset = testCase.Time_s < scenario.analysisStartTime_s;

            testCase.verifyEqual( ...
                testCase.Phase2BCombined.position_rad(preOnset), ...
                testCase.Phase2BNone.position_rad(preOnset), ...
                'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                testCase.Phase2BCombined.receivedMeasurement_rad(preOnset), ...
                testCase.Phase2BNone.receivedMeasurement_rad(preOnset), ...
                'AbsTol', 1e-12);
            testCase.verifyEqual( ...
                testCase.Phase2BCombined.command_V(preOnset), ...
                testCase.Phase2BNone.command_V(preOnset), ...
                'AbsTol', 1e-12);
        end

        function combinedOutputsAreFinite(testCase)
            timeSeries = testCase.Phase2BCombined.timeSeries;
            numericVariables = timeSeries(:, vartype("numeric"));
            testCase.verifyTrue(all(isfinite( ...
                table2array(numericVariables)), 'all'));
            testCase.verifyFalse(any(isnan( ...
                testCase.Phase2BCombined.state), 'all'));
            testCase.verifyFalse(any(isinf( ...
                testCase.Phase2BCombined.state), 'all'));
        end

        function recoveryMetricRequiresConfiguredDwell(testCase)
            params = testCase.Params;
            params.phase2b.metrics.recoveryThreshold_rad = 0.05;
            params.phase2b.metrics.recoveryDwellSamples = 3;
            time_s = (0:0.1:1).';
            scenario = phase2b_scenario("ground_offset", params);
            scenario.analysisStartTime_s = 0.2;
            scenario.analysisStopTime_s = 0.5;

            baseline.time_s = time_s;
            baseline.position_rad = zeros(size(time_s));
            baseline.command_V = zeros(size(time_s));
            baseline.receivedMeasurement_rad = zeros(size(time_s));

            deltaPosition = zeros(size(time_s));
            deltaPosition(time_s >= 0.2 & time_s < 0.5) = 0.10;
            deltaPosition(time_s >= 0.5 & time_s < 0.6) = 0.08;
            deltaPosition(time_s >= 0.6) = 0.01;
            fault = localSyntheticFaultResult( ...
                time_s, deltaPosition, scenario);
            [metrics, detail] = phase2b_metrics(fault, baseline, params);

            testCase.verifyEqual(metrics.recoveryTime_s, 0.1, ...
                'AbsTol', 10 * eps);
            testCase.verifyFalse(metrics.recoveryCensored);
            testCase.verifyEqual(detail.activeMask, ...
                time_s >= 0.2 & time_s < 0.5);

            fault.position_rad(time_s >= 0.5) = 0.10;
            censored = phase2b_metrics(fault, baseline, params);
            testCase.verifyTrue(censored.recoveryCensored);
            testCase.verifyTrue(isnan(censored.recoveryTime_s));
        end

        function unknownScenarioIsRejected(testCase)
            testCase.verifyError(@() phase2b_scenario( ...
                "not_a_phase2b_scenario", testCase.Params), ...
                'phase2b_scenario:UnknownScenario');
        end
    end
end

function result = localSyntheticFaultResult(time_s, position_rad, scenario)
n = numel(time_s);
result.time_s = time_s;
result.position_rad = position_rad;
result.command_V = zeros(n, 1);
result.receivedMeasurement_rad = zeros(n, 1);
result.scenario = scenario;
result.communication.packetDropped = false(n, 1);
result.communication.channelEnabled = false(n, 1);
result.communication.heldLast = false(n, 1);
result.communication.measurementAge_samples = zeros(n, 1);
end
