function [prediction,diagnostic] = edmd_predict(model,yHistory,uHistory,futureInputs)
%EDMD_PREDICT Free-run prediction given newest-first history and known inputs.
% yHistory=[y(k);...;y(k-d)], uHistory=[u(k-1);...;u(k-d)].
% futureInputs starts at u(k). No future measured outputs are consumed.
% Known future inputs make this a conditional forecast, not an autonomous one.
d=model.delay;
assert(isreal(yHistory) && isreal(uHistory) && isreal(futureInputs) && ...
    numel(yHistory)==d+1 && numel(uHistory)==d && ...
    isvector(futureInputs) && ~isempty(futureInputs) && ...
    all(isfinite([yHistory(:);uHistory(:);futureInputs(:)])), ...
    'EDMD:PredictionInput','Finite histories and a nonempty input sequence are required.');
h=[yHistory(:);uHistory(:)]; z=edmd_lift(model,h);
prediction=zeros(numel(futureInputs),1);
for j=1:numel(futureInputs)
    z=model.A*z+model.B*((futureInputs(j)-model.inputMean)/model.inputScale);
    prediction(j)=model.outputMean+model.C*z;
    assert(all(isfinite(z)) && isfinite(prediction(j)),'EDMD:Divergence', ...
        'The lifted forecast diverged; this forecast is unusable.');
end
diagnostic=struct('horizonSamples',numel(futureInputs), ...
    'horizonSeconds',numel(futureInputs)*model.sampleTime, ...
    'historyOutsideTrainingRange',any(h<model.training.minimumHistory | h>model.training.maximumHistory), ...
    'inputOutsideTrainingRange',any(futureInputs(:)<model.training.minimumInput | ...
        futureInputs(:)>model.training.maximumInput), ...
    'conditionalOnSuppliedInputs',true);
end
