function sc01a_write_manifest(p0,names,outputFolder)
%SC01A_WRITE_MANIFEST Export all case settings and physical parameter values.
arguments
    p0 (1,1) struct
    names (1,:) string
    outputFolder (1,1) string
end
cases=cell(numel(names),1); rows=cell(numel(names),1);
for k=1:numel(names)
    c=sc01a_case(names(k),p0);p=c.params;cases{k}=c;
    rows{k}=struct('Case',c.name,'CapacitiveExcitation',c.capacitive, ...
        'InductiveExcitation',c.inductive,'SharedCurrentExcitation',c.shared, ...
        'Polarity',c.polarity,'IntendedLogicSign',c.logicSign, ...
        'LogicTransitionOffset_s',c.logicTransitionOffset_s, ...
        'Periods',c.periods,'StopTime_s',c.stopTime_s, ...
        'VoltageStep_V',p.source.voltageStep_V,'CurrentStep_A',p.source.currentStep_A, ...
        'DriverRp_Ohm',p.driver.Rp_Ohm,'DriverRn_Ohm',p.driver.Rn_Ohm, ...
        'ReceiverCp_F',p.receiver.Cp_F,'ReceiverCn_F',p.receiver.Cn_F, ...
        'ReceiverRpBias_Ohm',p.receiver.RpBias_Ohm,'ReceiverRnBias_Ohm',p.receiver.RnBias_Ohm, ...
        'CouplingCp_F',p.coupling.Cp_F,'CouplingCn_F',p.coupling.Cn_F, ...
        'BehavioralMp_H',p.coupling.Mp_H,'BehavioralMn_H',p.coupling.Mn_H, ...
        'Provenance',p.meta.provenance);
end
manifest.schema="SC01A-CASE-MANIFEST-V1";
manifest.units="SI; suffixes indicate units; all physical inputs are assumed";
manifest.nullPolicy="Null logicTransitionOffset_s means no intended transition (NaN in MATLAB)";
manifest.sourceDefinition="Finite signed perturbations; polarity multiplies voltage/current amplitude. Complete time/value sources are in each raw MAT file.";
manifest.cases=vertcat(cases{:});
fid=fopen(fullfile(outputFolder,'sc01a_case_manifest.json'),'w','n','UTF-8');
assert(fid>=0,'SC01A:CannotWriteManifest','Cannot write case manifest.');
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s',jsonencode(manifest,PrettyPrint=true));
writetable(struct2table(vertcat(rows{:})),fullfile(outputFolder,'sc01a_case_manifest.csv'));
end
