function [sensor,packet]=fourway_v2_receiver_advance(sensor,tEnd,intendedTransitions)
if nargin<3||isempty(intendedTransitions),intendedTransitions=zeros(0,3);end
assert(size(intendedTransitions,2)==3&&all(isfinite(intendedTransitions),'all'));
assert(all(diff(intendedTransitions(:,1))>=0)&&all(intendedTransitions(:,1)>=sensor.state(1))&&all(intendedTransitions(:,1)<=tEnd));
assert(all(ismember(intendedTransitions(:,2:3),[0 1]),'all')&&isfinite(tEnd)&&tEnd>=sensor.state(1));
[sensor.state,events,decoder,boundaries,~,logic]=fourway_v2_exact(sensor.config,sensor.state,tEnd,intendedTransitions);
st=sensor.state;
packet=struct('count',st(11),'count_rad',st(11)*(2*pi/4096),'ideal_count',st(17), ...
    'domain_failed',logical(st(14)),'stress_failed',logical(st(22)),'numerical_rejected',logical(st(37)), ...
    'vp',st(2),'vn',st(3),'ir',st(4),'ideal_A',st(8),'ideal_B',st(9),'time_s',tEnd, ...
    'max_abs_common_mode_V',st(18),'max_abs_differential_V',st(19), ...
    'min_vp_V',st(29),'max_vp_V',st(30),'min_vn_V',st(31),'max_vn_V',st(32), ...
    'min_vd_V',st(33),'max_vd_V',st(34),'max_abs_ground_V',st(35), ...
    'first_domain_violation_s',st(24),'time_outside_domain_s',st(25),'time_outside_pin_s',st(72), ...
    'time_outside_differential_s',st(28));
if ~isempty(events),sensor.event_blocks{end+1}=events;end
if ~isempty(decoder),sensor.decoder_blocks{end+1}=decoder;end
if ~isempty(boundaries),sensor.boundary_blocks{end+1}=boundaries;end
if ~isempty(logic),sensor.logic_blocks{end+1}=logic;end
if ~isempty(intendedTransitions),sensor.intended_blocks{end+1}=intendedTransitions;end
sensor.packet_blocks{end+1}=[tEnd packet.count packet.count_rad packet.ideal_count packet.domain_failed packet.vp packet.vn packet.ir packet.ideal_A packet.ideal_B];
end
