function modelPath = build_phase3_simulink_model(runRecord, overwriteExisting)
%BUILD_PHASE3_SIMULINK_MODEL Independent discrete plant with shared loop logic.
% The S-function constructs the sensor/channel stream and executes the same
% observer, supervisor and controller decisions as the numerical simulation.
% Its input is the current output of a separate Simulink state-space plant;
% no recorded plant response or numerical command trajectory is replayed.
% Existing saved models are preserved unless overwriteExisting is explicit.

if nargin < 2, overwriteExisting = false; end
validateattributes(overwriteExisting, {'logical'}, {'scalar'});
matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(matlabRoot, 'functions'), fullfile(matlabRoot, 'parameters'));
localValidateRun(runRecord);
modelName = 'EMI_Resilient_Actuator_Phase3';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);
schema = 'PHASE3-INDEPENDENT-PLANT-V2-31';

% A loaded name takes precedence over a file path in Simulink. Check its
% identity before load_system, reconfiguration, or an explicit rebuild.
if bdIsLoaded(modelName)
    actualPath = get_param(modelName, 'FileName');
    assert(~isempty(actualPath) && ...
        strcmpi(char(java.io.File(actualPath).getCanonicalPath()), ...
        char(java.io.File(modelPath).getCanonicalPath())), ...
        'EMIProject:ActuatorModelPathMismatch', ...
        'The loaded %s belongs to a different project or is unsaved: %s', modelName, actualPath);
end
if isfile(modelPath) && ~overwriteExisting
    if ~bdIsLoaded(modelName), load_system(modelPath); end
    workspace = get_param(modelName, 'ModelWorkspace');
    assert(workspace.hasVariable('EMIPhase3ModelSchema'), ...
        'EMIProject:StalePhase3Model', ...
        'The saved Phase 3 model lacks its schema. Rebuild with explicit overwriteExisting=true.');
    metadata = workspace.getVariable('EMIPhase3ModelSchema');
    assert(isstruct(metadata) && isscalar(metadata) && isfield(metadata, 'schema') && ...
        strcmp(metadata.schema, schema), 'EMIProject:StalePhase3Model', ...
        'The saved Phase 3 model schema is stale. Rebuild with explicit overwriteExisting=true.');
    assert(strcmp(get_param([modelName, '/Causal Sensor and Protection Loop'], ...
        'FunctionName'), 'phase3_loop_sfun'), 'EMIProject:StalePhase3Model', ...
        'The saved Phase 3 loop block does not use phase3_loop_sfun.');
    localConfigure(modelName, runRecord);
    return
end
if bdIsLoaded(modelName), close_system(modelName, 0); end
load_system('simulink');
new_system(modelName);
% The Level-2 block evaluates its dialog while it is added. Define the
% model-workspace run before adding any block that references it.
localConfigure(modelName, runRecord);
workspace = get_param(modelName, 'ModelWorkspace');
assignin(workspace, 'EMIPhase3ModelSchema', struct('schema', schema));
set_param(modelName, 'Description', ...
    ['Phase 3 integration cross-check: independent discrete actual plant; ', ...
    'shared sensor, packet, observer, supervisor and controller logic. ', ...
    'This is not an independent implementation of the FDI algorithm.']);

add_block('simulink/Discrete/Discrete State-Space', ...
    [modelName, '/Independent Actual Actuator'], ...
    'Position', [500, 115, 655, 175], ...
    'A', 'phase3PlantA', 'B', 'phase3PlantB', ...
    'C', 'eye(3)', 'D', 'zeros(3,2)', ...
    'InitialCondition', 'phase3InitialPlantState', ...
    'SampleTime', 'phase3SampleTime_s');
add_block('simulink/User-Defined Functions/Level-2 MATLAB S-Function', ...
    [modelName, '/Causal Sensor and Protection Loop'], ...
    'Position', [160, 95, 365, 165], ...
    'FunctionName', 'phase3_loop_sfun', 'Parameters', 'phase3Run', ...
    'UserDataPersistent', 'off');
add_block('simulink/Signal Routing/Demux', ...
    [modelName, '/Command and Diagnostics'], ...
    'Position', [395, 103, 400, 165], 'Outputs', '[1 30]');
add_block('simulink/Sinks/Terminator', [modelName, '/Diagnostics Branch'], ...
    'Position', [430, 155, 450, 175]);
add_block('simulink/Sources/From Workspace', [modelName, '/Applied Load'], ...
    'Position', [245, 220, 365, 250], ...
    'VariableName', 'phase3LoadProfile', 'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value', ...
    'SampleTime', 'phase3SampleTime_s');
add_block('simulink/Signal Routing/Mux', [modelName, '/Plant Inputs'], ...
    'Position', [465, 115, 470, 185], 'Inputs', '2');
add_block('simulink/Sinks/To Workspace', [modelName, '/Log Actual Plant'], ...
    'Position', [715, 125, 855, 155], 'VariableName', 'phase3PlantSimout', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Decimation', '1');
add_block('simulink/Sinks/To Workspace', [modelName, '/Log Complete Loop'], ...
    'Position', [420, 300, 570, 330], 'VariableName', 'phase3LoopSimout', ...
    'SaveFormat', 'Structure With Time', 'MaxDataPoints', 'inf', 'Decimation', '1');

add_line(modelName, 'Independent Actual Actuator/1', ...
    'Causal Sensor and Protection Loop/1', 'autorouting', 'on');
add_line(modelName, 'Independent Actual Actuator/1', 'Log Actual Plant/1', 'autorouting', 'on');
add_line(modelName, 'Causal Sensor and Protection Loop/1', ...
    'Command and Diagnostics/1', 'autorouting', 'on');
add_line(modelName, 'Causal Sensor and Protection Loop/1', 'Log Complete Loop/1', 'autorouting', 'on');
add_line(modelName, 'Command and Diagnostics/1', 'Plant Inputs/1', 'autorouting', 'on');
add_line(modelName, 'Command and Diagnostics/2', 'Diagnostics Branch/1', 'autorouting', 'on');
add_line(modelName, 'Applied Load/1', 'Plant Inputs/2', 'autorouting', 'on');
add_line(modelName, 'Plant Inputs/1', 'Independent Actual Actuator/1', 'autorouting', 'on');
note = Simulink.Annotation(modelName, sprintf([ ...
    'Numerical integration validation only.\n', ...
    'Independent actual plant; shared causal sensor/channel and decision logic.\n', ...
    'True plant output enters sensor construction, never the monitor interface.\n', ...
    'Commands are computed online. No response trajectory is replayed.']));
note.Position = [45, 375];
localConfigure(modelName, runRecord);
if ~isfolder(fileparts(modelPath)), mkdir(fileparts(modelPath)); end
save_system(modelName, modelPath);
end

function localConfigure(modelName, runRecord)
plant = c2d(actuator_state_space(runRecord.scenario.actualParameters), ...
    runRecord.params.control.sampleTime_s, 'zoh');
[A, B, C, D] = ssdata(plant);
assert(isequal(C, eye(3)) && isequal(D, zeros(3, 2)), ...
    'EMIProject:InvalidPhase3Plant', 'Phase 3 requires the three-state, zero-feedthrough plant.');
workspace = get_param(modelName, 'ModelWorkspace');
assignin(workspace, 'phase3Run', runRecord);
assignin(workspace, 'phase3PlantA', A);
assignin(workspace, 'phase3PlantB', B);
assignin(workspace, 'phase3InitialPlantState', runRecord.scenario.initialPlantState(:));
assignin(workspace, 'phase3SampleTime_s', runRecord.params.control.sampleTime_s);
assignin(workspace, 'phase3LoadProfile', ...
    [runRecord.profiles.time_s, runRecord.profiles.loadTorque_Nm]);
set_param(modelName, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(runRecord.params.control.sampleTime_s, 17), ...
    'StartTime', '0', 'StopTime', num2str(runRecord.profiles.time_s(end), 17), ...
    'ReturnWorkspaceOutputs', 'on', 'SimulationMode', 'normal', ...
    'SaveTime', 'on', 'TimeSaveName', 'tout', ...
    'SaveOutput', 'off', 'SaveState', 'off', 'SaveFinalState', 'off', ...
    'SignalLogging', 'off', 'FastRestart', 'off');
end

function localValidateRun(r)
assert(isstruct(r) && isscalar(r) && ...
    all(isfield(r, {'params','scenario','profiles','configuration','protectionEnabled'})), ...
    'EMIProject:InvalidPhase3Run', 'A complete Phase 3 run record is required.');
validate_parameters(r.params);
validate_parameters(r.scenario.actualParameters);
validateattributes(r.scenario.initialPlantState, {'numeric'}, {'real','finite','numel',3});
validateattributes(r.protectionEnabled, {'logical','numeric'}, {'scalar','binary'});
ts = r.params.control.sampleTime_s;
t = r.profiles.time_s;
loadTorque = r.profiles.loadTorque_Nm;
expected = (0:round(r.params.simulation.stopTime_s / ts)).' * ts;
assert(isnumeric(t) && isreal(t) && iscolumn(t) && numel(t) >= 2 && ...
    all(isfinite(t)) && isequal(size(t), size(expected)) && ...
    max(abs(t-expected)) <= 32*eps(max(1, expected(end))) && ...
    abs(expected(end)-r.params.simulation.stopTime_s) <= 32*eps(max(1, expected(end))), ...
    'EMIProject:InvalidPhase3TimeGrid', 'Phase 3 profiles must cover the complete uniform configured sample grid.');
assert(isnumeric(loadTorque) && isreal(loadTorque) && ...
    isequal(size(loadTorque), size(t)) && all(isfinite(loadTorque)), ...
    'EMIProject:InvalidPhase3Load', 'Applied load must be a finite column on the complete sample grid.');
[values, names] = phase3_logged_values();
assert(numel(values) == 31 && numel(names) == 31 && ...
    string(names(1)) == "command_V" && string(names(8)) == "innovation_rad", ...
    'EMIProject:InvalidPhase3LogSchema', 'The Phase 3 model requires the declared 31-channel log schema.');
end
