function modelPath = build_phase2b_model(overwriteExisting)
%BUILD_PHASE2B_MODEL Generate the Phase 2B coupling/channel model.

if nargin < 1
    overwriteExisting = false;
end

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
validate_parameters(params);
continuousPlant = actuator_state_space(params);
controller = design_baseline_controller(params, continuousPlant);

modelName = 'EMI_Resilient_Actuator_Phase2B';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);

if isfile(modelPath) && ~overwriteExisting
    assert_actuator_model_schema(string(modelName),"phase2b");
    configure_phase2b_simulink_scenario("none",params);
    fprintf('Existing model preserved: %s\n', modelPath);
    return
end
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

load_system('simulink');
new_system(modelName);

[controllerA,controllerB,controllerC,controllerD] = ssdata(ss(controller.discrete));
plantDiscrete = ss(c2d(continuousPlant, ...
    params.control.sampleTime_s, 'zoh'));
[plantA, plantB, plantC, plantD] = ssdata(plantDiscrete);
sampleTimeText = num2str(params.control.sampleTime_s, 17);
maximumDelay = max(1,params.phase2b.communication.fixedDelay_samples + ...
    params.phase2b.communication.maximumJitter_samples);

add_block('simulink/Sources/Step', [modelName, '/Position Reference'], ...
    'Position', [30, 90, 80, 120], ...
    'Time', num2str(params.simulation.stepTime_s, 17), ...
    'Before', '0', ...
    'After', num2str(params.simulation.stepAmplitude_rad, 17), ...
    'SampleTime', sampleTimeText);

add_block('simulink/Math Operations/Sum', [modelName, '/Position Error'], ...
    'Position', [125, 86, 155, 124], 'Inputs', '+-');

localAddController([modelName,'/Discrete Position Controller'], ...
    controllerA,controllerB,controllerC,controllerD,sampleTimeText);
localAddDynamicLimit([modelName,'/Drive Voltage Limit']);

add_block('simulink/Discrete/Discrete State-Space', ...
    [modelName, '/Three-State Actuator Plant'], ...
    'Position', [450, 75, 565, 135], ...
    'A', mat2str(plantA, 17), ...
    'B', mat2str(plantB, 17), ...
    'C', mat2str(plantC, 17), ...
    'D', mat2str(plantD, 17), ...
    'InitialCondition', 'zeros(3,1)', ...
    'SampleTime', sampleTimeText);

add_block('simulink/Sources/Constant',[modelName,'/Nominal Load Torque'], ...
    'Position',[325,255,410,285], ...
    'Value',num2str(params.mechanical.nominalLoadTorque_Nm,17));
add_block('simulink/Signal Routing/Mux',[modelName,'/Plant Input Mux'], ...
    'Position',[425,80,430,150],'Inputs','2');
add_block('simulink/Sources/From Workspace',[modelName,'/Supply Profile'], ...
    'Position',[30,365,140,400],'VariableName','phase2bSupplyProfile', ...
    'Interpolate','off','OutputAfterFinalValue','Holding final value');
add_block('simulink/Signal Routing/Demux',[modelName,'/Supply Profile Demux'], ...
    'Position',[170,340,175,435],'Outputs','4');
add_block('simulink/Sources/Constant',[modelName,'/Supply Controller Reset Policy'], ...
    'Position',[30,455,160,485],'Value','0');
add_block('simulink/Sinks/To Workspace',[modelName,'/Log Supply'], ...
    'Position',[230,400,340,430],'VariableName','supplySimout', ...
    'SaveFormat','Structure With Time');
add_block('simulink/Sinks/To Workspace',[modelName,'/Log Controller State'], ...
    'Position',[350,455,490,485],'VariableName','controllerStateSimout', ...
    'SaveFormat','Structure With Time');
add_block('simulink/Sinks/Terminator',[modelName,'/Unused Supply Voltage'], ...
    'Position',[210,320,230,340]);
add_block('simulink/Sinks/Terminator',[modelName,'/Unused Supply Window'], ...
    'Position',[210,365,230,385]);

add_block('simulink/Signal Routing/Demux', ...
    [modelName, '/Plant Output Demux'], ...
    'Position', [600, 70, 605, 145], 'Outputs', '3');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Equivalent Physical Sensor Error'], ...
    'Position', [565, 190, 695, 225], ...
    'VariableName', 'phase2bEquivalentEncoderError', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Sensor-Side Measurement'], ...
    'Position', [735, 83, 765, 127], 'Inputs', '++');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Accepted Delay Samples'], ...
    'Position', [735, 205, 850, 240], ...
    'VariableName', 'phase2bAcceptedDelay', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName, '/Delay To Integer'], ...
    'Position', [875, 205, 950, 240], ...
    'OutDataTypeStr', 'uint32');

add_block('simulink/Discrete/Variable Integer Delay', ...
    [modelName, '/Timestamped Packet Delay'], ...
    'Position', [985, 78, 1095, 142], ...
    'DelayLengthSource', 'Input port', ...
    'DelayLengthUpperLimit', num2str(maximumDelay), ...
    'InitialConditionSource', 'Dialog', ...
    'InitialCondition', '0', ...
    'PreventDirectFeedthrough', 'off', ...
    'DiagnosticForDelayLength', 'Error', ...
    'SampleTime', sampleTimeText);

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Sample Received Mask'], ...
    'Position', [985, 205, 1095, 240], ...
    'VariableName', 'phase2bSampleReceived', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Routing/Switch', ...
    [modelName, '/Receiver Update Switch'], ...
    'Position', [1140, 80, 1195, 145], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '0.5');

add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Last Accepted Measurement'], ...
    'Position', [1125, 175, 1210, 205], ...
    'InitialCondition', '0', 'SampleTime', sampleTimeText);

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Phase 2B Diagnostics'], ...
    'Position', [885, 285, 1010, 320], ...
    'VariableName', 'phase2bDiagnostics', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Routing/Mux', [modelName, '/Result Mux'], ...
    'Position', [1310, 45, 1315, 255], 'Inputs', '10');
add_block('simulink/Sinks/Scope', [modelName, '/Phase 2B Scope'], ...
    'Position', [1370, 50, 1420, 85]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log Phase 2B Results'], ...
    'Position', [1360, 130, 1470, 170], ...
    'VariableName', 'phase2bSimout', ...
    'SaveFormat', 'Structure With Time');

add_line(modelName, 'Position Reference/1', 'Position Error/1', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Discrete Position Controller/1', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Drive Voltage Limit/1', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Plant Input Mux/1', 'autorouting', 'on');
add_line(modelName, 'Nominal Load Torque/1', 'Plant Input Mux/2', 'autorouting', 'on');
add_line(modelName, 'Plant Input Mux/1', 'Three-State Actuator Plant/1', 'autorouting', 'on');
add_line(modelName, 'Supply Profile/1', 'Supply Profile Demux/1', 'autorouting', 'on');
add_line(modelName, 'Supply Profile/1', 'Log Supply/1', 'autorouting', 'on');
add_line(modelName, 'Supply Profile Demux/1', 'Unused Supply Voltage/1', 'autorouting', 'on');
add_line(modelName, 'Supply Profile Demux/2', 'Drive Voltage Limit/2', 'autorouting', 'on');
add_line(modelName, 'Supply Profile Demux/3', 'Discrete Position Controller/2', 'autorouting', 'on');
add_line(modelName, 'Supply Profile Demux/4', 'Unused Supply Window/1', 'autorouting', 'on');
add_line(modelName, 'Supply Controller Reset Policy/1', 'Discrete Position Controller/3', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/2', 'Log Controller State/1', 'autorouting', 'on');
add_line(modelName, 'Three-State Actuator Plant/1', 'Plant Output Demux/1', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/1', 'Sensor-Side Measurement/1', 'autorouting', 'on');
add_line(modelName, 'Equivalent Physical Sensor Error/1', 'Sensor-Side Measurement/2', 'autorouting', 'on');
add_line(modelName, 'Sensor-Side Measurement/1', 'Timestamped Packet Delay/1', 'autorouting', 'on');
add_line(modelName, 'Accepted Delay Samples/1', 'Delay To Integer/1', 'autorouting', 'on');
add_line(modelName, 'Delay To Integer/1', 'Timestamped Packet Delay/2', 'autorouting', 'on');
add_line(modelName, 'Timestamped Packet Delay/1', 'Receiver Update Switch/1', 'autorouting', 'on');
add_line(modelName, 'Sample Received Mask/1', 'Receiver Update Switch/2', 'autorouting', 'on');
add_line(modelName, 'Last Accepted Measurement/1', 'Receiver Update Switch/3', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Last Accepted Measurement/1', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Position Error/2', 'autorouting', 'on');

add_line(modelName, 'Position Reference/1', 'Result Mux/1', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/1', 'Result Mux/2', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/2', 'Result Mux/3', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/3', 'Result Mux/4', 'autorouting', 'on');
add_line(modelName, 'Sensor-Side Measurement/1', 'Result Mux/5', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Result Mux/6', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Result Mux/7', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Result Mux/8', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Result Mux/9', 'autorouting', 'on');
add_line(modelName, 'Phase 2B Diagnostics/1', 'Result Mux/10', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Phase 2B Scope/1', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Log Phase 2B Results/1', 'autorouting', 'on');

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', sampleTimeText, ...
    'StopTime', num2str(params.simulation.stopTime_s, 17));

annotationText = sprintf([ ...
    'PHASE 2B: REDUCED-ORDER EMI COUPLING + PACKET CHANNEL\n', ...
    'Finite-edge physics sets receiver-equivalent disturbance levels.\n', ...
    'Timestamped packets use newest-valid-arrival, out-of-order rejection, and hold-last reception.\n', ...
    'Supply zero imposes zero terminal voltage; independently powered controller state holds or resets.']);
modelAnnotation = Simulink.Annotation(modelName, annotationText);
modelAnnotation.Position = [30, 300];

configuration = actuator_simulink_configuration(params,"phase2b");
modelWorkspace = get_param(modelName,'ModelWorkspace');
modelWorkspace.assignin('EMIActuatorModelSchema',configuration.schema);
save_system(modelName, modelPath);
configure_phase2b_simulink_scenario("none",params);
close_system(modelName, 0);
fprintf('Created Phase 2B Simulink model: %s\n', modelPath);
end

function localAddController(path,A,B,C,D,sampleTimeText)
% An explicit x[k+1] realization makes interruption hold/reset unambiguous.
add_block('built-in/Subsystem',path,'Position',[190,70,315,145]);
add_block('built-in/Inport',[path,'/Error'],'Position',[25,45,55,65],'Port','1');
add_block('built-in/Inport',[path,'/Drive Available'],'Position',[25,275,55,295],'Port','2');
add_block('built-in/Inport',[path,'/Reset Policy'],'Position',[25,345,55,365],'Port','3');
add_block('simulink/Discrete/Unit Delay',[path,'/Controller State'], ...
    'Position',[590,150,675,185],'SampleTime',sampleTimeText, ...
    'InitialCondition',mat2str(zeros(size(A,1),1),17));
names = {'State A','Error B','State C','Error D'};
values = {A,B,C,D};
positions = {[160,125,235,165],[160,40,235,80],[725,130,800,170],[725,30,800,70]};
for k=1:4
    add_block('simulink/Math Operations/Gain',[path,'/',names{k}], ...
        'Position',positions{k},'Gain',mat2str(values{k},17), ...
        'Multiplication','Matrix(K*u)');
end
add_block('simulink/Math Operations/Sum',[path,'/Candidate State'], ...
    'Position',[285,65,315,115],'Inputs','++');
add_block('simulink/Math Operations/Sum',[path,'/Raw Command'], ...
    'Position',[850,50,880,105],'Inputs','++');
add_block('simulink/Sources/Constant',[path,'/Zero State'], ...
    'Position',[180,230,240,260],'Value',mat2str(zeros(size(A,1),1),17));
add_block('simulink/Signal Routing/Switch',[path,'/Unavailable State'], ...
    'Position',[315,255,370,335],'Criteria','u2 >= Threshold','Threshold','0.5');
add_block('simulink/Signal Routing/Switch',[path,'/Next Controller State'], ...
    'Position',[455,115,510,200],'Criteria','u2 >= Threshold','Threshold','0.5');
add_block('built-in/Outport',[path,'/Command'],'Position',[925,65,955,85],'Port','1');
add_block('built-in/Outport',[path,'/State'],'Position',[725,215,755,235],'Port','2');
localLine(path,'Error/1','Error B/1');
localLine(path,'Error/1','Error D/1');
localLine(path,'Controller State/1','State A/1');
localLine(path,'Controller State/1','State C/1');
localLine(path,'Controller State/1','State/1');
localLine(path,'State A/1','Candidate State/1');
localLine(path,'Error B/1','Candidate State/2');
localLine(path,'State C/1','Raw Command/1');
localLine(path,'Error D/1','Raw Command/2');
localLine(path,'Raw Command/1','Command/1');
localLine(path,'Zero State/1','Unavailable State/1');
localLine(path,'Reset Policy/1','Unavailable State/2');
localLine(path,'Controller State/1','Unavailable State/3');
localLine(path,'Candidate State/1','Next Controller State/1');
localLine(path,'Drive Available/1','Next Controller State/2');
localLine(path,'Unavailable State/1','Next Controller State/3');
localLine(path,'Next Controller State/1','Controller State/1');
end

function localAddDynamicLimit(path)
add_block('built-in/Subsystem',path,'Position',[350,75,410,140]);
add_block('built-in/Inport',[path,'/Raw Command'],'Position',[25,45,55,65],'Port','1');
add_block('built-in/Inport',[path,'/Voltage Limit'],'Position',[25,125,55,145],'Port','2');
add_block('simulink/Math Operations/Gain',[path,'/Negative Limit'], ...
    'Position',[95,120,150,150],'Gain','-1');
add_block('simulink/Math Operations/MinMax',[path,'/Lower Bound'], ...
    'Position',[190,45,245,105],'Function','max','Inputs','2');
add_block('simulink/Math Operations/MinMax',[path,'/Upper Bound'], ...
    'Position',[300,45,355,105],'Function','min','Inputs','2');
add_block('built-in/Outport',[path,'/Applied Command'],'Position',[405,60,435,80]);
localLine(path,'Raw Command/1','Lower Bound/1');
localLine(path,'Voltage Limit/1','Negative Limit/1');
localLine(path,'Negative Limit/1','Lower Bound/2');
localLine(path,'Lower Bound/1','Upper Bound/1');
localLine(path,'Voltage Limit/1','Upper Bound/2');
localLine(path,'Upper Bound/1','Applied Command/1');
end

function localLine(path,source,destination)
add_line(path,source,destination,'autorouting','on');
end
