function modelPath = build_baseline_model(overwriteExisting)
%BUILD_BASELINE_MODEL Generate the clean Phase 1 Simulink model.
%
%   build_baseline_model          preserves an existing model.
%   build_baseline_model(true)    intentionally replaces it.

if nargin < 1
    overwriteExisting = false;
end

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
validate_parameters(params);
analyticalModel = baseline_closed_loop(params);

modelName = 'EMI_Resilient_Actuator_Baseline';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);

if isfile(modelPath) && ~overwriteExisting
    assert_actuator_model_schema(string(modelName),"baseline");
    fprintf('Existing model preserved: %s\n', modelPath);
    open_system(modelPath);
    return
end

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

load_system('simulink');
new_system(modelName);

controllerDiscrete = tf(analyticalModel.controller.discrete);
[controllerNum, controllerDen] = tfdata(controllerDiscrete, 'v');

plantDiscrete = ss(c2d( ...
    analyticalModel.plantContinuous(1,:), ...
    params.control.sampleTime_s, 'zoh'));
[plantA, plantB, plantC, plantD] = ssdata(plantDiscrete);

add_block('simulink/Sources/Step', [modelName, '/Position Reference'], ...
    'Position', [40, 95, 90, 125], ...
    'Time', num2str(params.simulation.stepTime_s, 17), ...
    'Before', '0', ...
    'After', num2str(params.simulation.stepAmplitude_rad, 17), ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Math Operations/Sum', [modelName, '/Position Error'], ...
    'Position', [135, 91, 165, 129], ...
    'Inputs', '+-');

add_block('simulink/Discrete/Discrete Transfer Fcn', ...
    [modelName, '/Discrete Position Controller'], ...
    'Position', [210, 85, 330, 135], ...
    'Numerator', mat2str(controllerNum, 17), ...
    'Denominator', mat2str(controllerDen, 17), ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/Drive Voltage Limit'], ...
    'Position', [375, 88, 435, 132], ...
    'UpperLimit', num2str(min(params.control.voltageLimit_V, params.electrical.nominalVoltage_V), 17), ...
    'LowerLimit', num2str(-min(params.control.voltageLimit_V, params.electrical.nominalVoltage_V), 17));

add_block('simulink/Discrete/Discrete State-Space', ...
    [modelName, '/Actuator Plant'], ...
    'Position', [485, 80, 600, 140], ...
    'A', mat2str(plantA, 17), ...
    'B', mat2str(plantB, 17), ...
    'C', mat2str(plantC, 17), ...
    'D', mat2str(plantD, 17), ...
    'InitialCondition', 'zeros(3,1)', ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Sources/Constant',[modelName,'/Nominal Load Torque'], ...
    'Position',[370,170,430,200], ...
    'Value',num2str(params.mechanical.nominalLoadTorque_Nm,17));
add_block('simulink/Signal Routing/Mux',[modelName,'/Plant Input Mux'], ...
    'Position',[455,85,460,155],'Inputs','2');

add_block('simulink/Math Operations/Gain', ...
    [modelName, '/EMI Fault Injection Placeholder'], ...
    'Position', [650, 88, 755, 132], ...
    'Gain', '1');

add_block('simulink/Signal Routing/Mux', [modelName, '/Result Mux'], ...
    'Position', [825, 43, 830, 117], ...
    'Inputs', '2');

add_block('simulink/Sinks/Scope', [modelName, '/Response Scope'], ...
    'Position', [885, 42, 935, 78]);

add_block('simulink/Sinks/To Workspace', [modelName, '/Log Results'], ...
    'Position', [875, 100, 955, 140], ...
    'VariableName', 'baselineSimout', ...
    'SaveFormat', 'Structure With Time');

add_line(modelName, 'Position Reference/1', 'Position Error/1', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Discrete Position Controller/1', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Drive Voltage Limit/1', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Plant Input Mux/1', 'autorouting', 'on');
add_line(modelName, 'Nominal Load Torque/1', 'Plant Input Mux/2', 'autorouting', 'on');
add_line(modelName, 'Plant Input Mux/1', 'Actuator Plant/1', 'autorouting', 'on');
add_line(modelName, 'Actuator Plant/1', 'EMI Fault Injection Placeholder/1', 'autorouting', 'on');
add_line(modelName, 'EMI Fault Injection Placeholder/1', 'Position Error/2', 'autorouting', 'on');
add_line(modelName, 'Position Reference/1', 'Result Mux/1', 'autorouting', 'on');
add_line(modelName, 'EMI Fault Injection Placeholder/1', 'Result Mux/2', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Response Scope/1', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Log Results/1', 'autorouting', 'on');

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(params.control.sampleTime_s, 17), ...
    'StopTime', num2str(params.simulation.stopTime_s, 17));

annotationText = sprintf([ ...
    'PHASE 1 CLEAN BASELINE\n', ...
    'Representative parameters only.\n', ...
    'The unity-gain EMI placeholder is replaced in Phase 2.']);
modelAnnotation = Simulink.Annotation(modelName, annotationText);
modelAnnotation.Position = [40, 190];

configuration = actuator_simulink_configuration(params,"baseline");
modelWorkspace = get_param(modelName,'ModelWorkspace');
modelWorkspace.assignin('EMIActuatorModelSchema',configuration.schema);
save_system(modelName, modelPath);
open_system(modelName);
fprintf('Created Simulink model: %s\n', modelPath);
end
