%RUN_PHASE2B_STUDY Run the isolated and combined Phase 2B fault cases.
% Results are always compared with the matched, all-faults-disabled case.

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
resultsFolder = fullfile(matlabRoot, 'results');
scenarioNames = [ ...
    "none", ...
    "capacitive_coupling", ...
    "inductive_coupling", ...
    "shared_impedance", ...
    "combined_coupling", ...
    "ground_offset", ...
    "communication_delay", ...
    "communication_jitter", ...
    "packet_loss", ...
    "combined_phase2b"];

scenarioCount = numel(scenarioNames);
studyResults = cell(scenarioCount, 1);
metricRecords = cell(scenarioCount, 1);
metricDetails = cell(scenarioCount, 1);
manifestRecords = cell(scenarioCount, 1);

baselineScenario = phase2b_scenario("none", params);
baselineResult = simulate_phase2b_actuator(params, baselineScenario);

for scenarioIndex = 1:scenarioCount
    scenario = phase2b_scenario(scenarioNames(scenarioIndex), params);
    result = simulate_phase2b_actuator(params, scenario);
    [metrics, detail] = phase2b_metrics(result, baselineResult, params);

    result.timeSeries.delta_position_rad = detail.deltaPosition_rad;
    result.timeSeries.delta_command_V = detail.deltaCommand_V;
    result.timeSeries.delta_received_measurement_rad = ...
        detail.deltaMeasurement_rad;
    result.timeSeries.pre_window_active = detail.preMask;
    result.timeSeries.analysis_window_active = detail.activeMask;
    result.timeSeries.post_window_active = detail.postMask;
    result.timeSeries.configured_fault_window_active = ...
        result.profile.configuredWindowActive;

    studyResults{scenarioIndex} = result;
    metricRecords{scenarioIndex} = metrics;
    metricDetails{scenarioIndex} = detail;
    manifestRecords{scenarioIndex} = localManifestRecord( ...
        result, params);

    outputName = char("phase2b_" + scenario.name + "_timeseries.csv");
    writetable(result.timeSeries, fullfile(resultsFolder, outputName));
end

phase2bMetrics = struct2table(vertcat(metricRecords{:}));
scenarioManifest = struct2table(vertcat(manifestRecords{:}));

writetable(phase2bMetrics, ...
    fullfile(resultsFolder, 'phase2b_metrics.csv'));
writetable(scenarioManifest, ...
    fullfile(resultsFolder, 'phase2b_scenario_manifest.csv'));
save(fullfile(resultsFolder, 'phase2b_fault_study.mat'), ...
    'params', 'scenarioNames', 'studyResults', 'phase2bMetrics', ...
    'scenarioManifest');

localCreateSummaryFigure(studyResults, metricDetails, scenarioNames, ...
    params, resultsFolder);

disp(phase2bMetrics);
fprintf('Phase 2B analytical study completed.\n');

function record = localManifestRecord(result, params)
scenario = result.scenario;
record.scenario = scenario.name;
record.description = scenario.description;
record.parameterSetId = params.meta.parameterSetId;
record.parameterProvenance = params.phase2b.meta.provenance;
record.capacitiveCouplingEnabled = ...
    scenario.coupling.capacitiveEnabled;
record.inductiveCouplingEnabled = ...
    scenario.coupling.inductiveEnabled;
record.sharedImpedanceEnabled = ...
    scenario.coupling.sharedImpedanceEnabled;
record.groundOffsetEnabled = scenario.groundOffset.enabled;
record.fixedDelayEnabled = ...
    scenario.communication.fixedDelayEnabled;
record.jitterEnabled = scenario.communication.jitterEnabled;
record.packetLossEnabled = ...
    scenario.communication.packetLossEnabled;
record.analysisStartTime_s = scenario.analysisStartTime_s;
record.analysisStopTime_s = scenario.analysisStopTime_s;
record.maxAbsReceiverDifferentialVoltage_V = max(abs( ...
    result.physical.receiverDifferentialVoltage_V));
record.receiverNoiseMargin_V = ...
    params.phase2b.receiver.differentialNoiseMargin_V;
record.receiverMarginExceeded = any( ...
    result.physical.receiverMarginExceeded);
record.maxTransmitDelay_samples = max( ...
    result.communication.transmitDelay_samples);
record.packetOpportunityCount = ...
    result.communication.transmittedPacketCount;
record.packetDropCount = result.communication.droppedPacketCount;
record.jitterRandomSeed = ...
    params.phase2b.communication.jitterRandomSeed;
record.packetLossRandomSeed = ...
    params.phase2b.communication.packetLossRandomSeed;
end

function localCreateSummaryFigure(results, details, names, params, outputFolder)
figureHandle = figure( ...
    'Color', 'white', ...
    'Name', 'Phase 2B Receiver Faults and Matched-Baseline Response', ...
    'Position', [80, 80, 1500, 920]);
layout = tiledlayout(2, 2, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

physicalNames = [ ...
    "capacitive_coupling", "inductive_coupling", ...
    "shared_impedance", "combined_coupling", ...
    "ground_offset", "combined_phase2b"];
communicationNames = [ ...
    "communication_delay", "communication_jitter", ...
    "packet_loss", "combined_phase2b"];

axesHandle = nexttile(layout);
hold(axesHandle, 'on');
for name = physicalNames
    index = find(names == name, 1);
    plot(results{index}.time_s, 1e3 .* ...
        results{index}.physical.receiverDifferentialVoltage_V, ...
        'LineWidth', 1.25, 'DisplayName', strrep(name, '_', ' '));
end
yline(axesHandle, 1e3 * params.phase2b.receiver.differentialNoiseMargin_V, ...
    '--', 'Noise margin', 'HandleVisibility', 'off');
yline(axesHandle, -1e3 * params.phase2b.receiver.differentialNoiseMargin_V, ...
    '--', 'HandleVisibility', 'off');
localFormatAxes(axesHandle, 'Receiver-equivalent differential faults', ...
    'Differential voltage (mV)', params);
localFormatLegend(legend(axesHandle, ...
    'Location', 'eastoutside', 'Interpreter', 'none'));

axesHandle = nexttile(layout);
hold(axesHandle, 'on');
for name = communicationNames
    index = find(names == name, 1);
    plot(results{index}.time_s, ...
        rad2deg(details{index}.deltaMeasurement_rad), ...
        'LineWidth', 1.25, 'DisplayName', strrep(name, '_', ' '));
end
localFormatAxes(axesHandle, ...
    'Received-measurement change vs. matched baseline', ...
    'Measurement delta (deg)', params);
localFormatLegend(legend(axesHandle, ...
    'Location', 'eastoutside', 'Interpreter', 'none'));

axesHandle = nexttile(layout);
hold(axesHandle, 'on');
for name = physicalNames
    index = find(names == name, 1);
    plot(results{index}.time_s, 1e3 .* ...
        rad2deg(details{index}.deltaPosition_rad), ...
        'LineWidth', 1.25, 'DisplayName', strrep(name, '_', ' '));
end
localFormatAxes(axesHandle, ...
    'Plant response to physical coupling and ground offset', ...
    'Position delta (mdeg)', params);
localFormatLegend(legend(axesHandle, ...
    'Location', 'eastoutside', 'Interpreter', 'none'));

axesHandle = nexttile(layout);
hold(axesHandle, 'on');
for name = communicationNames
    index = find(names == name, 1);
    plot(results{index}.time_s, 1e3 .* ...
        rad2deg(details{index}.deltaPosition_rad), ...
        'LineWidth', 1.25, 'DisplayName', strrep(name, '_', ' '));
end
localFormatAxes(axesHandle, ...
    'Plant response to communication faults', ...
    'Position delta (mdeg)', params);
localFormatLegend(legend(axesHandle, ...
    'Location', 'eastoutside', 'Interpreter', 'none'));

xLabelHandle = xlabel(layout, 'Time (s)');
titleHandle = title(layout, ...
    'Phase 2B: Receiver-Equivalent Faults and Matched-Baseline Deltas');
set(xLabelHandle, 'Color', [0.1, 0.1, 0.1]);
set(titleHandle, 'Color', [0.1, 0.1, 0.1]);
exportgraphics(figureHandle, fullfile(outputFolder, ...
    'phase2b_receiver_faults_and_response.png'), 'Resolution', 180);
close(figureHandle);
end

function localFormatAxes(axesHandle, plotTitle, yLabel, params)
grid(axesHandle, 'on');
xlim(axesHandle, [max(0, params.phase2b.communication.startTime_s - 0.10), ...
    params.simulation.stopTime_s]);
xLabelHandle = xlabel(axesHandle, 'Time (s)');
yLabelHandle = ylabel(axesHandle, yLabel);
titleHandle = title(axesHandle, plotTitle);
set(axesHandle, ...
    'Color', 'white', ...
    'XColor', [0.1, 0.1, 0.1], ...
    'YColor', [0.1, 0.1, 0.1], ...
    'GridColor', [0.78, 0.78, 0.78]);
set(xLabelHandle, 'Color', [0.1, 0.1, 0.1]);
set(yLabelHandle, 'Color', [0.1, 0.1, 0.1]);
set(titleHandle, 'Color', [0.1, 0.1, 0.1]);
end

function localFormatLegend(legendHandle)
set(legendHandle, ...
    'Color', 'white', ...
    'TextColor', [0.1, 0.1, 0.1], ...
    'EdgeColor', [0.35, 0.35, 0.35]);
end
