function validationTable = validate_phase2b_simulink(outputFolder)
%VALIDATE_PHASE2B_SIMULINK Cross-check all 29 logged channels for each scenario.
arguments
    outputFolder (1,1) string = ""
end

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(matlabRoot,'functions'));
outputFolder=prepare_fresh_output_folder(outputFolder, ...
    fullfile(matlabRoot,'results','development'),"phase2b_validation");
run(fullfile(matlabRoot, 'startup_project.m'));
oldConfig=Simulink.fileGenControl('getConfig');
cacheCleanup=onCleanup(@()Simulink.fileGenControl('setConfig','config',oldConfig));
Simulink.fileGenControl('set','CacheFolder',fullfile(outputFolder,'cache'), ...
    'CodeGenFolder',fullfile(outputFolder,'codegen'),'createDir',true);
params = actuator_parameters();
modelName = 'EMI_Resilient_Actuator_Phase2B';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);
if ~isfile(modelPath), build_phase2b_model(false); end
load_system(modelPath);
modelCleanup = onCleanup(@() close_system(modelName, 0));
scenarioNames = ["none", "capacitive_coupling", "inductive_coupling", ...
    "shared_impedance", "combined_coupling", "ground_offset", ...
    "communication_delay", "communication_jitter", "packet_loss", "combined_phase2b"];
channelNames = ["Reference_rad", "Position_rad", "Velocity_rad_s", "Current_A", ...
    "Sensor_rad", "Received_rad", "TrackingError_rad", "RawCommand_V", "Command_V", ...
    "EquivalentEncoderError_rad", "CapacitiveCurrent_A", "CapacitiveVoltage_V", ...
    "InductiveVoltage_V", "SharedImpedanceVoltage_V", "GroundCommonModeVoltage_V", ...
    "GroundDifferentialVoltage_V", "ReceiverDifferentialVoltage_V", ...
    "SourceWindowActive", "GroundWindowActive", "ChannelEnabled", ...
    "TransmitDelay_samples", "PacketDropped", "SampleReceived", ...
    "AcceptedSourceIndex", "AcceptedDelay_samples", "HeldLast", ...
    "MeasurementAge_samples", "CollisionDiscardCount", "OutOfOrderDiscardCount"];
expectedSamples = round(params.simulation.stopTime_s / params.control.sampleTime_s) + 1;
tolerance = params.phase2b.metrics.crossValidationTolerance_rad;
rows = cell(numel(scenarioNames), 1);
detailTables = cell(numel(scenarioNames), 1);
for scenarioIndex = 1:numel(scenarioNames)
    name = scenarioNames(scenarioIndex);
    scenario = phase2b_scenario(name, params);
    analytical = simulate_phase2b_actuator(params, scenario);
    simulationInput = create_phase2b_simulation_input(modelName, params, scenario);
    simulationOutput = sim(simulationInput);
    logged = simulationOutput.get('phase2bSimout');
    % Reconstruct every expected diagnostic from the analytical result,
    % independently of the timeseries supplied to the Simulink logging mux.
    p = analytical.physical;
    c = analytical.communication;
    diagnostics = [p.equivalentEncoderError_rad, p.capacitiveCurrent_A, ...
        p.capacitiveVoltage_V, p.inductiveVoltage_V, p.sharedImpedanceVoltage_V, ...
        p.groundCommonModeVoltage_V, p.groundDifferentialVoltage_V, ...
        p.receiverDifferentialVoltage_V, double(p.sourceWindowActive), ...
        double(p.groundWindowActive), double(c.channelEnabled), ...
        c.transmitDelay_samples, double(c.packetDropped), double(c.sampleReceived), ...
        c.acceptedSourceIndex, c.acceptedDelay_samples, double(c.heldLast), ...
        c.measurementAge_samples, c.collisionDiscardCount, c.outOfOrderDiscardCount];
    expected = [analytical.reference_rad, analytical.position_rad, ...
        analytical.velocity_rad_s, analytical.current_A, ...
        analytical.sensorSideMeasurement_rad, analytical.receivedMeasurement_rad, ...
        analytical.trackingError_rad, analytical.unsaturatedCommand_V, ...
        analytical.command_V, diagnostics];
    [check, channels] = compare_logged_arrays(logged.time, logged.signals.values, ...
        analytical.time_s, expected, channelNames, tolerance, 18:29, expectedSamples);
    d = check.MaxDifferences;
    row = struct('Scenario', name, 'LoggedSamples', check.LoggedSamples, ...
        'MaxTimeDifference_s', check.MaxTimeDifference_s, ...
        'MaxReferenceDifference_rad', d(1), 'MaxPositionDifference_rad', d(2), ...
        'MaxVelocityDifference_rad_s', d(3), 'MaxCurrentDifference_A', d(4), ...
        'MaxSensorDifference_rad', d(5), 'MaxReceivedDifference_rad', d(6), ...
        'MaxCommandDifference_V', d(9), 'MaxDiagnosticDifference', max(d(10:29)), ...
        'DiscreteProfilesExact', check.DiscreteProfilesExact, ...
        'MaxTrackingErrorDifference_rad', d(7), 'MaxRawCommandDifference_V', d(8), ...
        'ExpectedSamples', check.ExpectedSamples, 'DimensionsValid', check.DimensionsValid, ...
        'AllFinite', check.AllFinite, 'TimeStrictlyIncreasing', check.TimeStrictlyIncreasing, ...
        'Passed', check.Passed, 'Diagnostic', check.Diagnostic);
    rows{scenarioIndex} = row;
    detailTables{scenarioIndex} = addvars(channels, ...
        repmat(name, height(channels), 1), 'Before', 1, 'NewVariableNames', 'Scenario');
end
validationTable = struct2table(vertcat(rows{:}));
% Failed finite/dimension/time/channel gates remain available for diagnosis.
writetable(validationTable, fullfile(outputFolder, 'phase2b_simulink_validation.csv'));
writetable(vertcat(detailTables{:}), fullfile(outputFolder, 'phase2b_simulink_validation_channels.csv'));
disp(validationTable);
assert(all(validationTable.Passed), 'EMIProject:Phase2BSimulinkCrossValidationFailed', ...
    ['Phase 2B analytical/Simulink validation failed. All 29 channels must be ', ...
    'finite and agree on a complete strictly increasing time grid; columns ', ...
    '18:29 must match exactly. See validation CSVs.']);
fprintf('Phase 2B analytical/Simulink cross-validation passed.\n');
clear modelCleanup
end
