%RUN_PHASE2_FAULT_STUDY Compare independently enabled encoder faults.

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
scenarioNames = ["none", "gaussian", "sinusoidal", "count_jump", "dropout"];
scenarioCount = numel(scenarioNames);
studyResults = cell(scenarioCount, 1);
metricRecords = cell(scenarioCount, 1);
resultsFolder = fullfile(matlabRoot, 'results');

for scenarioIndex = 1:scenarioCount
    scenario = encoder_fault_scenario( ...
        scenarioNames(scenarioIndex), params);
    studyResults{scenarioIndex} = ...
        simulate_faulted_actuator(params, scenario);
    metricRecords{scenarioIndex} = studyResults{scenarioIndex}.metrics;

    outputStem = char("phase2_" + scenarioNames(scenarioIndex));
    writetable(studyResults{scenarioIndex}.timeSeries, ...
        fullfile(resultsFolder, [outputStem, '_timeseries.csv']));
end

phase2Metrics = struct2table(vertcat(metricRecords{:}));
writetable(phase2Metrics, ...
    fullfile(resultsFolder, 'phase2_metrics.csv'));
save(fullfile(resultsFolder, 'phase2_fault_study.mat'), ...
    'params', 'scenarioNames', 'studyResults', 'phase2Metrics');

figureHandle = figure( ...
    'Color', 'white', ...
    'Name', 'Phase 2 Encoder Fault Study', ...
    'Position', [100, 100, 1200, 1100]);
layout = tiledlayout(scenarioCount, 1, ...
    'TileSpacing', 'compact', 'Padding', 'compact');

for scenarioIndex = 1:scenarioCount
    axesHandle = nexttile(layout);
    result = studyResults{scenarioIndex};
    plot(result.timeSeries.time_s, ...
        rad2deg(result.timeSeries.theta_ref_rad), '--', ...
        'LineWidth', 1.0);
    hold on;
    plot(result.timeSeries.time_s, ...
        rad2deg(result.timeSeries.theta_rad), ...
        'LineWidth', 1.3);
    plot(result.timeSeries.time_s, ...
        rad2deg(result.timeSeries.theta_measured_rad), ':', ...
        'LineWidth', 1.0);
    grid on;
    ylabel('deg');
    titleHandle = title(strrep(scenarioNames(scenarioIndex), '_', ' '));
    set(axesHandle, ...
        'Color', 'white', ...
        'XColor', [0.1, 0.1, 0.1], ...
        'YColor', [0.1, 0.1, 0.1], ...
        'GridColor', [0.75, 0.75, 0.75]);
    set(titleHandle, 'Color', [0.1, 0.1, 0.1]);

    if scenarioIndex == 1
        legendHandle = legend( ...
            ["Reference", "True position", "Measured position"], ...
            'Location', 'best');
        set(legendHandle, ...
            'Color', 'white', ...
            'TextColor', [0.1, 0.1, 0.1], ...
            'EdgeColor', [0.3, 0.3, 0.3]);
    end
end

xlabel(layout, 'Time (s)');
title(layout, 'Phase 2: Encoder Faults Inside the Feedback Loop');
exportgraphics(figureHandle, ...
    fullfile(resultsFolder, 'phase2_encoder_faults.png'), ...
    'Resolution', 180);

disp(phase2Metrics);
fprintf('Phase 2 analytical fault study completed.\n');
