function modelPath = build_phase2_model(overwriteExisting)
%BUILD_PHASE2_MODEL Generate the Phase 2 Simulink encoder-fault model.
%
%   build_phase2_model          preserves an existing model.
%   build_phase2_model(true)    intentionally replaces it.

if nargin < 1
    overwriteExisting = false;
end

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
validate_parameters(params);
analyticalModel = baseline_closed_loop(params);
configure_phase2_simulink_fault(params.faults.defaultScenario);

modelName = 'EMI_Resilient_Actuator_Phase2';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);

if isfile(modelPath) && ~overwriteExisting
    fprintf('Existing model preserved: %s\n', modelPath);
    open_system(modelPath);
    return
end

if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

load_system('simulink');
new_system(modelName);

controllerDiscrete = tf(analyticalModel.controller.discrete);
[controllerNum, controllerDen] = tfdata(controllerDiscrete, 'v');

plantDiscrete = ss(c2d( ...
    analyticalModel.positionPlantContinuous, ...
    params.control.sampleTime_s, 'zoh'));
[plantA, plantB, plantC, plantD] = ssdata(plantDiscrete);

add_block('simulink/Sources/Step', [modelName, '/Position Reference'], ...
    'Position', [35, 90, 85, 120], ...
    'Time', num2str(params.simulation.stepTime_s, 17), ...
    'Before', '0', ...
    'After', num2str(params.simulation.stepAmplitude_rad, 17), ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Math Operations/Sum', [modelName, '/Position Error'], ...
    'Position', [125, 86, 155, 124], ...
    'Inputs', '+-');

add_block('simulink/Discrete/Discrete Transfer Fcn', ...
    [modelName, '/Discrete Position Controller'], ...
    'Position', [195, 80, 315, 130], ...
    'Numerator', mat2str(controllerNum, 17), ...
    'Denominator', mat2str(controllerDen, 17), ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/Drive Voltage Limit'], ...
    'Position', [355, 83, 415, 127], ...
    'UpperLimit', num2str(params.control.voltageLimit_V, 17), ...
    'LowerLimit', num2str(-params.control.voltageLimit_V, 17));

add_block('simulink/Discrete/Discrete State-Space', ...
    [modelName, '/Actuator Plant'], ...
    'Position', [455, 75, 570, 135], ...
    'A', mat2str(plantA, 17), ...
    'B', mat2str(plantB, 17), ...
    'C', mat2str(plantC, 17), ...
    'D', mat2str(plantD, 17), ...
    'InitialCondition', 'zeros(3,1)', ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Encoder Additive Fault'], ...
    'Position', [480, 190, 580, 225], ...
    'VariableName', 'encoderAdditiveFault', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Raw Encoder Measurement'], ...
    'Position', [625, 82, 655, 128], ...
    'Inputs', '++');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Encoder Dropout Mask'], ...
    'Position', [625, 205, 730, 240], ...
    'VariableName', 'encoderDropoutMask', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Routing/Switch', ...
    [modelName, '/Dropout Hold Switch'], ...
    'Position', [755, 80, 810, 140], ...
    'Criteria', 'u2 >= Threshold', ...
    'Threshold', '0.5');

add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Last Accepted Encoder'], ...
    'Position', [735, 165, 815, 195], ...
    'InitialCondition', '0', ...
    'SampleTime', num2str(params.control.sampleTime_s, 17));

add_block('simulink/Signal Routing/Mux', [modelName, '/Result Mux'], ...
    'Position', [895, 45, 900, 165], ...
    'Inputs', '5');

add_block('simulink/Sinks/Scope', [modelName, '/Phase 2 Scope'], ...
    'Position', [955, 45, 1005, 80]);

add_block('simulink/Sinks/To Workspace', [modelName, '/Log Phase 2 Results'], ...
    'Position', [940, 115, 1040, 155], ...
    'VariableName', 'phase2Simout', ...
    'SaveFormat', 'Structure With Time');

add_line(modelName, 'Position Reference/1', 'Position Error/1', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Discrete Position Controller/1', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Drive Voltage Limit/1', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Actuator Plant/1', 'autorouting', 'on');
add_line(modelName, 'Actuator Plant/1', 'Raw Encoder Measurement/1', 'autorouting', 'on');
add_line(modelName, 'Encoder Additive Fault/1', 'Raw Encoder Measurement/2', 'autorouting', 'on');
add_line(modelName, 'Last Accepted Encoder/1', 'Dropout Hold Switch/1', 'autorouting', 'on');
add_line(modelName, 'Encoder Dropout Mask/1', 'Dropout Hold Switch/2', 'autorouting', 'on');
add_line(modelName, 'Raw Encoder Measurement/1', 'Dropout Hold Switch/3', 'autorouting', 'on');
add_line(modelName, 'Dropout Hold Switch/1', 'Last Accepted Encoder/1', 'autorouting', 'on');
add_line(modelName, 'Dropout Hold Switch/1', 'Position Error/2', 'autorouting', 'on');
add_line(modelName, 'Position Reference/1', 'Result Mux/1', 'autorouting', 'on');
add_line(modelName, 'Actuator Plant/1', 'Result Mux/2', 'autorouting', 'on');
add_line(modelName, 'Dropout Hold Switch/1', 'Result Mux/3', 'autorouting', 'on');
add_line(modelName, 'Encoder Additive Fault/1', 'Result Mux/4', 'autorouting', 'on');
add_line(modelName, 'Encoder Dropout Mask/1', 'Result Mux/5', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Phase 2 Scope/1', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Log Phase 2 Results/1', 'autorouting', 'on');

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', num2str(params.control.sampleTime_s, 17), ...
    'StopTime', num2str(params.simulation.stopTime_s, 17));

annotationText = sprintf([ ...
    'PHASE 2 ENCODER FAULT INJECTION\n', ...
    'Additive fault and dropout profiles are loaded from the workspace.\n', ...
    'Default scenario: none.']);
modelAnnotation = Simulink.Annotation(modelName, annotationText);
modelAnnotation.Position = [35, 275];

save_system(modelName, modelPath);
open_system(modelName);
fprintf('Created Phase 2 Simulink model: %s\n', modelPath);
end

