function modelPath = build_phase2b_model(overwriteExisting)
%BUILD_PHASE2B_MODEL Generate the Phase 2B coupling/channel model.

if nargin < 1
    overwriteExisting = false;
end

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
validate_parameters(params);
continuousPlant = actuator_state_space(params);
controller = design_baseline_controller(params, continuousPlant);
configure_phase2b_simulink_scenario("none", params);

modelName = 'EMI_Resilient_Actuator_Phase2B';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);

if isfile(modelPath) && ~overwriteExisting
    fprintf('Existing model preserved: %s\n', modelPath);
    return
end
if bdIsLoaded(modelName)
    close_system(modelName, 0);
end

load_system('simulink');
new_system(modelName);

controllerDiscrete = tf(controller.discrete);
[controllerNum, controllerDen] = tfdata(controllerDiscrete, 'v');
plantDiscrete = ss(c2d(continuousPlant(:, 1), ...
    params.control.sampleTime_s, 'zoh'));
[plantA, plantB, plantC, plantD] = ssdata(plantDiscrete);
sampleTimeText = num2str(params.control.sampleTime_s, 17);
maximumDelay = params.phase2b.communication.fixedDelay_samples + ...
    params.phase2b.communication.maximumJitter_samples;

add_block('simulink/Sources/Step', [modelName, '/Position Reference'], ...
    'Position', [30, 90, 80, 120], ...
    'Time', num2str(params.simulation.stepTime_s, 17), ...
    'Before', '0', ...
    'After', num2str(params.simulation.stepAmplitude_rad, 17), ...
    'SampleTime', sampleTimeText);

add_block('simulink/Math Operations/Sum', [modelName, '/Position Error'], ...
    'Position', [125, 86, 155, 124], 'Inputs', '+-');

add_block('simulink/Discrete/Discrete Transfer Fcn', ...
    [modelName, '/Discrete Position Controller'], ...
    'Position', [190, 80, 310, 130], ...
    'Numerator', mat2str(controllerNum, 17), ...
    'Denominator', mat2str(controllerDen, 17), ...
    'SampleTime', sampleTimeText);

add_block('simulink/Discontinuities/Saturation', ...
    [modelName, '/Drive Voltage Limit'], ...
    'Position', [350, 83, 410, 127], ...
    'UpperLimit', num2str(params.control.voltageLimit_V, 17), ...
    'LowerLimit', num2str(-params.control.voltageLimit_V, 17));

add_block('simulink/Discrete/Discrete State-Space', ...
    [modelName, '/Three-State Actuator Plant'], ...
    'Position', [450, 75, 565, 135], ...
    'A', mat2str(plantA, 17), ...
    'B', mat2str(plantB, 17), ...
    'C', mat2str(plantC, 17), ...
    'D', mat2str(plantD, 17), ...
    'InitialCondition', 'zeros(3,1)', ...
    'SampleTime', sampleTimeText);

add_block('simulink/Signal Routing/Demux', ...
    [modelName, '/Plant Output Demux'], ...
    'Position', [600, 70, 605, 145], 'Outputs', '3');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Equivalent Physical Sensor Error'], ...
    'Position', [565, 190, 695, 225], ...
    'VariableName', 'phase2bEquivalentEncoderError', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Math Operations/Sum', ...
    [modelName, '/Sensor-Side Measurement'], ...
    'Position', [735, 83, 765, 127], 'Inputs', '++');

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Accepted Delay Samples'], ...
    'Position', [735, 205, 850, 240], ...
    'VariableName', 'phase2bAcceptedDelay', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Attributes/Data Type Conversion', ...
    [modelName, '/Delay To Integer'], ...
    'Position', [875, 205, 950, 240], ...
    'OutDataTypeStr', 'uint32');

add_block('simulink/Discrete/Variable Integer Delay', ...
    [modelName, '/Timestamped Packet Delay'], ...
    'Position', [985, 78, 1095, 142], ...
    'DelayLengthSource', 'Input port', ...
    'DelayLengthUpperLimit', num2str(maximumDelay), ...
    'InitialConditionSource', 'Dialog', ...
    'InitialCondition', '0', ...
    'PreventDirectFeedthrough', 'off', ...
    'DiagnosticForDelayLength', 'Error', ...
    'SampleTime', sampleTimeText);

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Sample Received Mask'], ...
    'Position', [985, 205, 1095, 240], ...
    'VariableName', 'phase2bSampleReceived', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Routing/Switch', ...
    [modelName, '/Receiver Update Switch'], ...
    'Position', [1140, 80, 1195, 145], ...
    'Criteria', 'u2 >= Threshold', 'Threshold', '0.5');

add_block('simulink/Discrete/Unit Delay', ...
    [modelName, '/Last Accepted Measurement'], ...
    'Position', [1125, 175, 1210, 205], ...
    'InitialCondition', '0', 'SampleTime', sampleTimeText);

add_block('simulink/Sources/From Workspace', ...
    [modelName, '/Phase 2B Diagnostics'], ...
    'Position', [885, 285, 1010, 320], ...
    'VariableName', 'phase2bDiagnostics', ...
    'Interpolate', 'off', ...
    'OutputAfterFinalValue', 'Holding final value');

add_block('simulink/Signal Routing/Mux', [modelName, '/Result Mux'], ...
    'Position', [1310, 45, 1315, 255], 'Inputs', '10');
add_block('simulink/Sinks/Scope', [modelName, '/Phase 2B Scope'], ...
    'Position', [1370, 50, 1420, 85]);
add_block('simulink/Sinks/To Workspace', ...
    [modelName, '/Log Phase 2B Results'], ...
    'Position', [1360, 130, 1470, 170], ...
    'VariableName', 'phase2bSimout', ...
    'SaveFormat', 'Structure With Time');

add_line(modelName, 'Position Reference/1', 'Position Error/1', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Discrete Position Controller/1', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Drive Voltage Limit/1', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Three-State Actuator Plant/1', 'autorouting', 'on');
add_line(modelName, 'Three-State Actuator Plant/1', 'Plant Output Demux/1', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/1', 'Sensor-Side Measurement/1', 'autorouting', 'on');
add_line(modelName, 'Equivalent Physical Sensor Error/1', 'Sensor-Side Measurement/2', 'autorouting', 'on');
add_line(modelName, 'Sensor-Side Measurement/1', 'Timestamped Packet Delay/1', 'autorouting', 'on');
add_line(modelName, 'Accepted Delay Samples/1', 'Delay To Integer/1', 'autorouting', 'on');
add_line(modelName, 'Delay To Integer/1', 'Timestamped Packet Delay/2', 'autorouting', 'on');
add_line(modelName, 'Timestamped Packet Delay/1', 'Receiver Update Switch/1', 'autorouting', 'on');
add_line(modelName, 'Sample Received Mask/1', 'Receiver Update Switch/2', 'autorouting', 'on');
add_line(modelName, 'Last Accepted Measurement/1', 'Receiver Update Switch/3', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Last Accepted Measurement/1', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Position Error/2', 'autorouting', 'on');

add_line(modelName, 'Position Reference/1', 'Result Mux/1', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/1', 'Result Mux/2', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/2', 'Result Mux/3', 'autorouting', 'on');
add_line(modelName, 'Plant Output Demux/3', 'Result Mux/4', 'autorouting', 'on');
add_line(modelName, 'Sensor-Side Measurement/1', 'Result Mux/5', 'autorouting', 'on');
add_line(modelName, 'Receiver Update Switch/1', 'Result Mux/6', 'autorouting', 'on');
add_line(modelName, 'Position Error/1', 'Result Mux/7', 'autorouting', 'on');
add_line(modelName, 'Discrete Position Controller/1', 'Result Mux/8', 'autorouting', 'on');
add_line(modelName, 'Drive Voltage Limit/1', 'Result Mux/9', 'autorouting', 'on');
add_line(modelName, 'Phase 2B Diagnostics/1', 'Result Mux/10', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Phase 2B Scope/1', 'autorouting', 'on');
add_line(modelName, 'Result Mux/1', 'Log Phase 2B Results/1', 'autorouting', 'on');

set_param(modelName, ...
    'SolverType', 'Fixed-step', ...
    'Solver', 'FixedStepDiscrete', ...
    'FixedStep', sampleTimeText, ...
    'StopTime', num2str(params.simulation.stopTime_s, 17));

annotationText = sprintf([ ...
    'PHASE 2B: REDUCED-ORDER EMI COUPLING + PACKET CHANNEL\n', ...
    'Finite-edge physics sets receiver-equivalent disturbance levels.\n', ...
    'Timestamped packets use newest-valid-arrival, out-of-order rejection, and hold-last reception.']);
modelAnnotation = Simulink.Annotation(modelName, annotationText);
modelAnnotation.Position = [30, 300];

save_system(modelName, modelPath);
close_system(modelName, 0);
fprintf('Created Phase 2B Simulink model: %s\n', modelPath);
end
