function validationTable = validate_phase2b_simulink()
%VALIDATE_PHASE2B_SIMULINK Cross-check every analytical/Simulink scenario.

scriptPath = mfilename('fullpath');
matlabRoot = fileparts(fileparts(scriptPath));
run(fullfile(matlabRoot, 'startup_project.m'));

params = actuator_parameters();
modelName = 'EMI_Resilient_Actuator_Phase2B';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);
if ~isfile(modelPath)
    build_phase2b_model(false);
end
load_system(modelPath);
modelCleanup = onCleanup(@() close_system(modelName, 0));

scenarioNames = [ ...
    "none", "capacitive_coupling", "inductive_coupling", ...
    "shared_impedance", "combined_coupling", "ground_offset", ...
    "communication_delay", "communication_jitter", ...
    "packet_loss", "combined_phase2b"];
scenarioCount = numel(scenarioNames);

loggedSamples = zeros(scenarioCount, 1);
maxTimeDifference_s = zeros(scenarioCount, 1);
maxReferenceDifference_rad = zeros(scenarioCount, 1);
maxPositionDifference_rad = zeros(scenarioCount, 1);
maxVelocityDifference_rad_s = zeros(scenarioCount, 1);
maxCurrentDifference_A = zeros(scenarioCount, 1);
maxSensorDifference_rad = zeros(scenarioCount, 1);
maxReceivedDifference_rad = zeros(scenarioCount, 1);
maxCommandDifference_V = zeros(scenarioCount, 1);
maxDiagnosticDifference = zeros(scenarioCount, 1);
discreteProfilesExact = false(scenarioCount, 1);

for scenarioIndex = 1:scenarioCount
    scenario = phase2b_scenario(scenarioNames(scenarioIndex), params);
    analytical = simulate_phase2b_actuator(params, scenario);
    [simulationInput, signals] = create_phase2b_simulation_input( ...
        modelName, params, scenario);
    simulationOutput = sim(simulationInput);
    logged = simulationOutput.get('phase2bSimout');
    values = logged.signals.values;
    diagnostics = signals.phase2bDiagnostics.Data;

    loggedSamples(scenarioIndex) = size(values, 1);
    maxTimeDifference_s(scenarioIndex) = max(abs( ...
        logged.time - analytical.time_s));
    maxReferenceDifference_rad(scenarioIndex) = max(abs( ...
        values(:, 1) - analytical.reference_rad));
    maxPositionDifference_rad(scenarioIndex) = max(abs( ...
        values(:, 2) - analytical.position_rad));
    maxVelocityDifference_rad_s(scenarioIndex) = max(abs( ...
        values(:, 3) - analytical.velocity_rad_s));
    maxCurrentDifference_A(scenarioIndex) = max(abs( ...
        values(:, 4) - analytical.current_A));
    maxSensorDifference_rad(scenarioIndex) = max(abs( ...
        values(:, 5) - analytical.sensorSideMeasurement_rad));
    maxReceivedDifference_rad(scenarioIndex) = max(abs( ...
        values(:, 6) - analytical.receivedMeasurement_rad));
    maxCommandDifference_V(scenarioIndex) = max(abs( ...
        values(:, 9) - analytical.command_V));
    maxDiagnosticDifference(scenarioIndex) = max(abs( ...
        values(:, 10:17) - diagnostics(:, 1:8)), [], 'all');
    discreteProfilesExact(scenarioIndex) = isequal( ...
        values(:, 18:29), diagnostics(:, 9:20));
end

validationTable = table( ...
    scenarioNames.', loggedSamples, maxTimeDifference_s, ...
    maxReferenceDifference_rad, maxPositionDifference_rad, ...
    maxVelocityDifference_rad_s, maxCurrentDifference_A, ...
    maxSensorDifference_rad, maxReceivedDifference_rad, ...
    maxCommandDifference_V, maxDiagnosticDifference, ...
    discreteProfilesExact, ...
    'VariableNames', { ...
    'Scenario', 'LoggedSamples', 'MaxTimeDifference_s', ...
    'MaxReferenceDifference_rad', 'MaxPositionDifference_rad', ...
    'MaxVelocityDifference_rad_s', 'MaxCurrentDifference_A', ...
    'MaxSensorDifference_rad', 'MaxReceivedDifference_rad', ...
    'MaxCommandDifference_V', 'MaxDiagnosticDifference', ...
    'DiscreteProfilesExact'});

tolerance = params.phase2b.metrics.crossValidationTolerance_rad;
numericDifferences = validationTable{:, 3:11};
if any(numericDifferences > tolerance, 'all') || ...
        ~all(discreteProfilesExact) || ...
        any(loggedSamples ~= round(params.simulation.stopTime_s / ...
        params.control.sampleTime_s) + 1)
    error('EMIProject:Phase2BSimulinkCrossValidationFailed', ...
        'Phase 2B analytical/Simulink comparison exceeded its acceptance gate.');
end

writetable(validationTable, fullfile(matlabRoot, 'results', ...
    'phase2b_simulink_validation.csv'));
disp(validationTable);
fprintf('Phase 2B analytical/Simulink cross-validation passed.\n');
clear modelCleanup
end
