function validationTable = validate_phase2b_sensitivity(study, outputFolder)
%VALIDATE_PHASE2B_SENSITIVITY Check selected sweep cases against saved Simulink.
% The saved model embeds the baseline plant, controller, reference and timing.
% Only Phase 2B parameters may vary. All logged channels are checked against
% the analytical simulation, including raw/limited drive and 20 diagnostics.

arguments
    study (1,1) struct
    outputFolder (1,1) string
end

matlabRoot = fileparts(fileparts(mfilename('fullpath')));
run(fullfile(matlabRoot, 'startup_project.m'));
baseline = actuator_parameters();
assert(isfield(study, 'validationCases') && ...
    isstruct(study.validationCases) && ~isempty(study.validationCases), ...
    'EMIProject:MissingSensitivityValidationCases', ...
    'study.validationCases must contain at least one validation case.');
cases = study.validationCases;
assert(all(isfield(cases, {'label', 'params', 'scenario'})), ...
    'EMIProject:InvalidSensitivityValidationCase', ...
    'Each validation case must contain label, params and scenario.');

% Reject unsupported sweep changes before opening or simulating the model.
fixedGroups = {'electrical', 'motor', 'mechanical', 'sensor', ...
    'control', 'simulation'};
for caseIndex = 1:numel(cases)
    for groupIndex = 1:numel(fixedGroups)
        group = fixedGroups{groupIndex};
        assert(isfield(cases(caseIndex).params, group) && ...
            isequaln(cases(caseIndex).params.(group), baseline.(group)), ...
            'EMIProject:SensitivityModelParameterMismatch', ...
            ['Case %s changes the fixed %s parameter group. The saved ', ...
            'model requires actuator_parameters baseline plant, ', ...
            'controller, sensor, reference and sample timing.'], ...
            char(string(cases(caseIndex).label)), group);
    end
end

modelName = 'EMI_Resilient_Actuator_Phase2B';
modelPath = fullfile(matlabRoot, 'models', [modelName, '.slx']);
assert(isfile(modelPath), 'EMIProject:MissingSensitivityValidationModel', ...
    'The saved Phase 2B model is required: %s', modelPath);
load_system(modelPath);
modelCleanup = onCleanup(@() close_system(modelName, 0));
maximumModelDelay = str2double(get_param( ...
    [modelName, '/Timestamped Packet Delay'], 'DelayLengthUpperLimit'));
assert(isfinite(maximumModelDelay), ...
    'EMIProject:InvalidSensitivityModelDelay', ...
    'The saved model must have a finite numeric delay upper limit.');

quantityNames = { ...
    'Time_s', 'Reference_rad', 'Position_rad', 'Velocity_rad_s', ...
    'Current_A', 'Sensor_rad', 'Received_rad', 'TrackingError_rad', ...
    'RawCommand_V', 'LimitedCommand_V', ...
    'EquivalentEncoderError_rad', 'CapacitiveCurrent_A', ...
    'CapacitiveVoltage_V', 'InductiveVoltage_V', ...
    'SharedImpedanceVoltage_V', 'GroundCommonModeVoltage_V', ...
    'GroundDifferentialVoltage_V', 'ReceiverDifferentialVoltage_V', ...
    'SourceWindowActive', 'GroundWindowActive', 'ChannelEnabled', ...
    'TransmitDelay_samples', 'PacketDropped', 'SampleReceived', ...
    'AcceptedSourceIndex', 'AcceptedDelay_samples', 'HeldLast', ...
    'MeasurementAge_samples', 'CollisionDiscardCount', ...
    'OutOfOrderDiscardCount'};
caseCount = numel(cases);
labels = strings(caseCount, 1);
loggedSamples = zeros(caseCount, 1);
expectedSamples = zeros(caseCount, 1);
maxDifferences = zeros(caseCount, numel(quantityNames));
allFinite = false(caseCount, 1);
discreteProfilesExact = false(caseCount, 1);
tolerance = 1e-9;

for caseIndex = 1:caseCount
    labels(caseIndex) = string(cases(caseIndex).label);
    params = cases(caseIndex).params;
    scenario = cases(caseIndex).scenario;
    analytical = simulate_phase2b_actuator(params, scenario);
    [simulationInput, signals] = create_phase2b_simulation_input( ...
        modelName, params, scenario);
    assert(all(signals.communication.acceptedDelay_samples <= ...
        maximumModelDelay), 'EMIProject:SensitivityModelDelayExceeded', ...
        'Case %s exceeds the saved model delay capacity (%g samples).', ...
        char(labels(caseIndex)), maximumModelDelay);
    simulationOutput = sim(simulationInput);
    logged = simulationOutput.get('phase2bSimout');
    values = logged.signals.values;

    physical = analytical.physical;
    communication = analytical.communication;
    diagnostics = [ ...
        physical.equivalentEncoderError_rad, ...
        physical.capacitiveCurrent_A, physical.capacitiveVoltage_V, ...
        physical.inductiveVoltage_V, physical.sharedImpedanceVoltage_V, ...
        physical.groundCommonModeVoltage_V, ...
        physical.groundDifferentialVoltage_V, ...
        physical.receiverDifferentialVoltage_V, ...
        double(physical.sourceWindowActive), ...
        double(physical.groundWindowActive), ...
        double(communication.channelEnabled), ...
        communication.transmitDelay_samples, ...
        double(communication.packetDropped), ...
        double(communication.sampleReceived), ...
        communication.acceptedSourceIndex, ...
        communication.acceptedDelay_samples, ...
        double(communication.heldLast), communication.measurementAge_samples, ...
        communication.collisionDiscardCount, ...
        communication.outOfOrderDiscardCount];
    expected = [analytical.reference_rad, analytical.position_rad, ...
        analytical.velocity_rad_s, analytical.current_A, ...
        analytical.sensorSideMeasurement_rad, ...
        analytical.receivedMeasurement_rad, analytical.trackingError_rad, ...
        analytical.unsaturatedCommand_V, analytical.command_V, diagnostics];
    expectedSamples(caseIndex) = round(params.simulation.stopTime_s / ...
        params.control.sampleTime_s) + 1;
    loggedSamples(caseIndex) = size(values, 1);
    assert(isequal(size(values), [expectedSamples(caseIndex), 29]) && ...
        isequal(size(expected), size(values)) && ...
        numel(logged.time) == expectedSamples(caseIndex) && ...
        numel(analytical.time_s) == expectedSamples(caseIndex), ...
        'EMIProject:SensitivityValidationSampleMismatch', ...
        'Case %s has incorrect sample count or logged-channel dimensions.', ...
        char(labels(caseIndex)));
    actualWithTime = [logged.time(:), values];
    expectedWithTime = [analytical.time_s(:), expected];
    allFinite(caseIndex) = all(isfinite(actualWithTime), 'all') && ...
        all(isfinite(expectedWithTime), 'all');
    if allFinite(caseIndex)
        maxDifferences(caseIndex, :) = max( ...
            abs(actualWithTime - expectedWithTime), [], 1);
    else
        maxDifferences(caseIndex, :) = Inf;
    end
    discreteProfilesExact(caseIndex) = isequal( ...
        values(:, 18:29), diagnostics(:, 9:20));
    fprintf('Sensitivity Simulink check %d/%d: %s, maximum difference %.3g\n', ...
        caseIndex, caseCount, labels(caseIndex), ...
        max(maxDifferences(caseIndex, :)));
end

passed = allFinite & discreteProfilesExact & ...
    loggedSamples == expectedSamples & all(maxDifferences <= tolerance, 2);
validationTable = table(labels, expectedSamples, loggedSamples, ...
    allFinite, discreteProfilesExact, passed, ...
    'VariableNames', {'Case', 'ExpectedSamples', 'LoggedSamples', ...
    'AllFinite', 'DiscreteProfilesExact', 'Passed'});
differenceNames = strcat('MaxDifference_', quantityNames);
validationTable = [validationTable, ...
    array2table(maxDifferences, 'VariableNames', differenceNames)];
if ~isfolder(outputFolder)
    mkdir(outputFolder);
end
writetable(validationTable, fullfile(outputFolder, ...
    'phase2b_sensitivity_simulink_validation.csv'));
assert(all(passed), 'EMIProject:Phase2BSensitivityCrossValidationFailed', ...
    ['Sensitivity analytical/Simulink validation failed. Each numeric ', ...
    'channel must be finite and agree within 1e-9; discrete diagnostic ', ...
    'profiles and sample counts must match exactly. See the validation CSV.']);
fprintf('All %d sensitivity analytical/Simulink comparisons passed.\n', ...
    caseCount);
end
