function write_phase2b_sensitivity_summary(study, tests, outputFolder)
%WRITE_PHASE2B_SENSITIVITY_SUMMARY Write a report from the stored run evidence.
arguments
    study (1,1) struct
    tests
    outputFolder (1,1) string
end
fid = fopen(fullfile(outputFolder,'Phase2B_Sensitivity_Summary.md'),'w','n','UTF-8');
assert(fid>=0,'EMIProject:CannotWriteSensitivitySummary','Could not open summary.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'# Phase 2B Sensitivity Study\n\n');
fprintf(fid,'Completed: %s. MATLAB %s. Parameter set: `%s`.\n\n', ...
    study.metadata.createdUTC,study.metadata.matlabVersion,study.metadata.parameterSetId);
fprintf(fid,['The parameter-sensitivity milestone is complete for the existing reduced-order model. ', ...
    'The study identifies which assumptions matter within the chosen ranges, ', ...
    'preserves reproducible inputs and results, and defines the evidence needed for the next circuit model. ', ...
    'No hardware parameters were identified or experimentally validated.\n\n']);
fprintf(fid,'## Execution and verification\n\n');
fprintf(fid,'| Check | Result |\n|---|---:|\n');
fprintf(fid,'| Study simulations | %d |\n',study.metadata.studyClosedLoopRuns);
fprintf(fid,'| Parameter controls screened | %d |\n',height(study.catalog));
fprintf(fid,'| One-at-a-time runs, both contexts | %d |\n',height(study.oat));
fprintf(fid,'| Stratified parameter sets | %d, each in two contexts |\n',height(study.globalInputs));
fprintf(fid,'| Two interaction grids | %d runs |\n',height(study.grid));
fprintf(fid,'| Low/nominal/high no-fault regressions | %d passed |\n',height(study.noFaultRegression));
fprintf(fid,'| Automated project tests | %d / %d passed |\n',nnz([tests.Passed]),numel(tests));
fprintf(fid,'| Selected MATLAB/Simulink comparisons | %d / %d passed |\n',nnz(study.validation.Passed),height(study.validation));
fprintf(fid,'| Largest checked numerical difference | %.5g |\n',max(study.validation{:,7:end},[],'all'));
fprintf(fid,'| Numerical tolerance | 1e-9 in each logged quantity''s unit |\n');
fprintf(fid,'| Analytical study runtime (excluding tests/plotting/Simulink) | %.1f s |\n\n',study.metadata.elapsedSeconds);
fprintf(fid,['All study trajectories were finite. Every study run matched the clean trajectory before the shared analysis window. ', ...
    'The no-fault parameter checks had a largest position/received-measurement/command difference of %.3g. ', ...
    'Selected Simulink checks used 1,501 samples each, all 29 logged channels plus time, and exact discrete diagnostics. ', ...
    'The selected comparisons are representative checks, not Simulink execution of every sweep point.\n\n'], ...
    max(study.noFaultRegression.MaxNoFaultDifference));

fprintf(fid,'## Which assumptions changed position the most?\n\n');
fprintf(fid,['This ranking holds all other inputs at their nominal values and uses loss-free communication. ', ...
    'It ranks the largest whole-record position change from the nominal faulted trajectory. ', ...
    'It depends on the chosen ranges and is not a normalized or universal importance ranking.\n\n']);
fprintf(fid,'| Assumption | Explored range | Largest change from nominal (deg) |\n|---|---|---:|\n');
ranked = study.ranking(study.ranking.Context=="physical_only" & study.ranking.Role=="response",:);
for j = 1:min(10,height(ranked))
    definition = study.catalog(study.catalog.Key==ranked.Parameter(j),:);
    fprintf(fid,'| %s | %.5g to %.5g %s | %.6f |\n',ranked.Label(j), ...
        definition.Low,definition.High,definition.Unit,ranked.MaxTrajectoryChange_deg(j));
end
fprintf(fid,['\nGround-reference disturbance, conversion into differential error, the assumed voltage-to-angle bridge ', ...
    'and the envelope frequency deserve early attention in this design. The bridge is phenomenological: ', ...
    'its strong sensitivity is a reason to replace it with receiver/decoder evidence before interpreting angular error as a real prediction. ', ...
    'The measured transfer of ground/common-mode disturbance should be characterized alongside it.\n\n']);
fprintf(fid,['At the nominal source slope, the shared-return equation contains a 75 mV resistive term and ', ...
    'a 300 mV inductive term before differential conversion. Independent tests confirmed the expected ', ...
    '1.2x total after doubling resistance alone and 1.8x after doubling inductance alone. ', ...
    'This 20%%/80%% split is conditional on the assumed 3 A commutation step and 200 ns rise time.\n\n']);

fprintf(fid,'## Combined assumptions reveal larger modeled errors\n\n');
fprintf(fid,['Both contexts use the same **[0.70, 1.15) s** analysis window and matched no-fault baseline. ', ...
    'The fixed communication realization can amplify or partly cancel physical disturbances; ', ...
    'a smaller metric in one case is not evidence that packet faults improve the system.\n\n']);
fprintf(fid,'| Measure | Physical channels only | With fixed communication faults |\n|---|---:|---:|\n');
first = study.globalMetrics(study.globalMetrics.Context=="physical_only",:);
second = study.globalMetrics(study.globalMetrics.Context=="combined_phase2b",:);
nominal = study.oat(study.oat.Parameter=="angle_sensitivity" & study.oat.Value==study.oat.NominalValue,:);
n1 = nominal(nominal.Context=="physical_only",:);
n2 = nominal(nominal.Context=="combined_phase2b",:);
fprintf(fid,'| Nominal active peak position delta (deg) | %.6f | %.6f |\n',n1.ActivePeak_deg,n2.ActivePeak_deg);
fprintf(fid,'| Largest sampled active peak position delta (deg) | %.6f | %.6f |\n',max(first.ActivePeak_deg),max(second.ActivePeak_deg));
fprintf(fid,'| Largest sampled active position RMSE (deg) | %.6f | %.6f |\n',max(first.ActiveRMSE_deg),max(second.ActiveRMSE_deg));
fprintf(fid,'| Largest sampled receiver differential peak (V) | %.6f | %.6f |\n',max(first.ReceiverPeak_V),max(second.ReceiverPeak_V));
fprintf(fid,'| Cases without observed recovery by record end | %d / %d | %d / %d |\n',nnz(first.RecoveryCensored),height(first),nnz(second.RecoveryCensored),height(second));
fprintf(fid,'| Cases crossing the assumed 0.20 V diagnostic margin | %d / %d | %d / %d |\n',nnz(first.MarginExceededSamples),height(first),nnz(second.MarginExceededSamples),height(second));
fprintf(fid,'| Cases with active/post-window command saturation | %d | %d |\n\n', ...
    nnz(first.ActiveSaturatedSamples | first.PostSaturatedSamples),nnz(second.ActiveSaturatedSamples | second.PostSaturatedSamples));
fprintf(fid,['The extrema in different rows may come from different parameter sets. ', ...
    'All 512 input vectors and their matched results are saved; selected extreme time histories are also exported. ', ...
    'These are finite, assumed exploration ranges. Counts in this table are not real-world probabilities, ', ...
    'and the largest sampled result is not a guaranteed worst case. A 0.20 V diagnostic crossing does not trigger ', ...
    'a count error in this model. Finite unsaturated trajectories do not establish a stability guarantee.\n\n']);
fprintf(fid,['Recovery uses a 0.05-degree tolerance sustained for 50 samples. The record ends at 1.50 s, ', ...
    'leaving 0.35 s after the study window. Censored recovery means that required dwell was not observed in this record; ', ...
    'it does not prove permanent failure. A zero value means the response already meets the configured tolerance.\n\n']);

fprintf(fid,'## Model limitations exposed by the sweep\n\n');
fprintf(fid,['- Noise margin and common-mode limit change flags only; they do not change controller feedback.\n', ...
    '- Receiver differential capacitance changes a reported pole but does not filter the waveform.\n', ...
    '- PWM frequency, fall time, pulse-width setting and count cap are inactive. Equal changes to both line capacitances or both mutual inductances preserve the differential imbalance. Their negligible effects here are implementation facts, not physical conclusions.\n', ...
    '- Receiver bandwidth acts at the envelope frequency. The low-bandwidth cases describe a hypothetical baseband filter, not measured nanosecond receiver behavior.\n', ...
    '- Fixed phases and a largely settled step trajectory limit generalization; moving-trajectory and phase studies remain future work.\n\n']);
fprintf(fid,'## Next engineering work\n\n');
fprintf(fid,['1. Identify the ground-to-differential transfer and receiver/encoder behavior; record intended signal levels, common-mode movement and decoded counts against an independent position reference.\n', ...
    '2. Identify shared-return impedance, actual source edges and paired-line imbalance. Use independently measured transfer data to avoid fitting several confounded scalar factors from the same position trace.\n', ...
    '3. Implement the proposed **SC-01A finite-edge electrical harness** with explicit loading and return paths, then establish numerical convergence. The companion circuit specification contains the required evidence and primary-source references.\n\n', ...
    'The SC-01 specification is prepared; the circuit is not yet implemented. Supply interruption remains a separate unfinished Phase 2 mechanism. Phase 3 fault detection and resilient control are still future work.\n\n']);
fprintf(fid,'## Files and rerun\n\n');
fprintf(fid,['Run `phase2b_sensitivity_main` from `03_MATLAB`. The workflow recreates the tests, design, metrics, ', ...
    'figure, selected Simulink comparisons, MAT archive and this summary in `results/sensitivity`.\n\n', ...
    '- `phase2b_sensitivity_catalog.csv`: exact ranges, units, scale and implementation roles.\n', ...
    '- `phase2b_sensitivity_oat.csv` and `phase2b_sensitivity_ranking.csv`: one-at-a-time results.\n', ...
    '- `phase2b_sensitivity_global_inputs.csv` and `phase2b_sensitivity_global_metrics.csv`: paired design and results.\n', ...
    '- `phase2b_sensitivity_interaction_grids.csv`: controlled response surfaces.\n', ...
    '- `phase2b_sensitivity_study.mat`: full input structures, metrics and validation case definitions.\n', ...
    '- `phase2b_sensitivity_case_*.csv`: selected time histories.\n', ...
    '- `phase2b_sensitivity_tests.csv`, `phase2b_sensitivity_no_fault_regression.csv`, and `phase2b_sensitivity_simulink_validation.csv`: verification evidence.\n', ...
    '- `phase2b_sensitivity_overview.png`: checked four-panel figure.\n', ...
    '- `04_EMI_Models/Phase2B_Sensitivity_Method.md`: design and metric definitions.\n', ...
    '- `04_EMI_Models/Parameter_Identification_and_Switching_Case.md`: input-evidence plan and proposed next circuit.\n']);
end
