function assert_actuator_model_schema(modelName, kind)
%ASSERT_ACTUATOR_MODEL_SCHEMA Reject stale or wrong-project saved models.
arguments
    modelName (1,1) string
    kind (1,1) string
end
matlabRoot = fileparts(fileparts(mfilename('fullpath')));
expectedPath = fullfile(matlabRoot,'models',char(modelName + ".slx"));
assert(isfile(expectedPath),'EMIProject:MissingActuatorModel', ...
    'Build the %s model before simulation: %s',char(kind),expectedPath);
if ~bdIsLoaded(char(modelName))
    % Load from the owning project, not the caller's MATLAB path. Loading is
    % read-only; run overrides never change model or base-workspace values.
    load_system(expectedPath);
end
actualPath = get_param(char(modelName),'FileName');
assert(strcmpi(char(java.io.File(actualPath).getCanonicalPath()), ...
    char(java.io.File(expectedPath).getCanonicalPath())), ...
    'EMIProject:ActuatorModelPathMismatch', ...
    'The loaded %s belongs to a different project: %s',char(modelName),actualPath);
workspace = get_param(char(modelName),'ModelWorkspace');
assert(workspace.hasVariable('EMIActuatorModelSchema'), ...
    'EMIProject:StaleActuatorModel', ...
    'The saved %s model has no current schema. Rebuild it explicitly before simulation.',char(kind));
schema = workspace.getVariable('EMIActuatorModelSchema');
assert(isstruct(schema) && isscalar(schema) && ...
    isfield(schema,'id') && isfield(schema,'kind') && ...
    strcmp(string(schema.id),"EMI-ACTUATOR-PARAMETERIZED-V2") && ...
    strcmp(string(schema.kind),kind), ...
    'EMIProject:StaleActuatorModel', ...
    'The saved %s model has an old schema. Rebuild it explicitly before simulation.', ...
    char(kind));
end
