function [check, channels] = compare_logged_arrays(actualTime, actual, ...
    expectedTime, expected, channelNames, tolerance, exactColumns, expectedSamples)
%COMPARE_LOGGED_ARRAYS Fail-closed comparison of complete sampled records.
% Invalid arrays return failed evidence rather than throwing, so callers can
% save their detailed validation table before raising a campaign failure.
% Times must be finite, strictly increasing columns on the expected grid.
% Every declared channel is checked; exact columns have zero allowance.

channelNames = reshape(string(channelNames), 1, []);
channelCount = numel(channelNames);
assert(channelCount > 0 && numel(unique(channelNames)) == channelCount && ...
    isnumeric(tolerance) && isreal(tolerance) && isscalar(tolerance) && ...
    isfinite(tolerance) && tolerance >= 0 && ...
    isnumeric(expectedSamples) && isscalar(expectedSamples) && ...
    isfinite(expectedSamples) && expectedSamples >= 2 && ...
    expectedSamples == fix(expectedSamples) && isnumeric(exactColumns) && ...
    all(isfinite(exactColumns)) && all(exactColumns == fix(exactColumns)) && ...
    all(exactColumns >= 1 & exactColumns <= channelCount), ...
    'EMIProject:InvalidComparisonContract', 'Invalid logged-array comparison contract.');

check.ExpectedSamples = expectedSamples;
check.LoggedSamples = size(actual, 1);
check.DimensionsValid = realMatrix(actual) && realMatrix(expected) && ...
    isequal(size(actual), [expectedSamples, channelCount]) && ...
    isequal(size(expected), [expectedSamples, channelCount]) && ...
    realMatrix(actualTime) && realMatrix(expectedTime) && ...
    isequal(size(actualTime), [expectedSamples, 1]) && ...
    isequal(size(expectedTime), [expectedSamples, 1]);
check.AllFinite = finiteArray(actual) && finiteArray(expected) && ...
    finiteArray(actualTime) && finiteArray(expectedTime);
check.TimeStrictlyIncreasing = check.DimensionsValid && ...
    finiteArray(actualTime) && finiteArray(expectedTime) && ...
    all(diff(actualTime) > 0) && all(diff(expectedTime) > 0);
check.MaxTimeDifference_s = Inf;
check.MaxDifferences = Inf(1, channelCount);
exactRequired = false(1, channelCount);
exactRequired(exactColumns) = true;
allowances = repmat(tolerance, 1, channelCount);
allowances(exactRequired) = 0;
check.DiscreteProfilesExact = false;
if check.DimensionsValid
    if finiteArray(actualTime) && finiteArray(expectedTime)
        check.MaxTimeDifference_s = max(abs(double(actualTime) - double(expectedTime)));
    end
    for column = 1:channelCount
        if all(isfinite(actual(:, column))) && all(isfinite(expected(:, column)))
            check.MaxDifferences(column) = max(abs(double(actual(:, column)) - double(expected(:, column))));
        end
    end
    check.DiscreteProfilesExact = all(isfinite(check.MaxDifferences(exactRequired))) && ...
        all(check.MaxDifferences(exactRequired) == 0);
end
check.TimePassed = check.TimeStrictlyIncreasing && ...
    isfinite(check.MaxTimeDifference_s) && check.MaxTimeDifference_s <= tolerance;
check.ChannelsPassed = isfinite(check.MaxDifferences) & ...
    check.MaxDifferences <= allowances;
check.Passed = check.DimensionsValid && check.AllFinite && ...
    check.TimePassed && check.DiscreteProfilesExact && all(check.ChannelsPassed);
issues = strings(0, 1);
if ~check.DimensionsValid, issues(end+1) = "sample_count_or_dimensions"; end
if ~check.AllFinite, issues(end+1) = "nonfinite_or_nonreal_record"; end
if ~check.TimePassed, issues(end+1) = "invalid_or_misaligned_time"; end
if ~check.DiscreteProfilesExact, issues(end+1) = "discrete_profile_mismatch"; end
if ~all(check.ChannelsPassed), issues(end+1) = "channel_mismatch_or_invalid_data"; end
check.Diagnostic = strjoin(issues, "; ");
channels = table(channelNames.', exactRequired.', check.MaxDifferences.', ...
    allowances.', check.ChannelsPassed.', ...
    'VariableNames', {'Channel', 'ExactRequired', 'MaxAbsoluteDifference', ...
    'Allowance', 'ChannelPassed'});
end

function valid = realMatrix(value)
valid = (isnumeric(value) || islogical(value)) && isreal(value) && ismatrix(value);
end

function valid = finiteArray(value)
valid = realMatrix(value) && ~isempty(value) && all(isfinite(value), 'all');
end
