function [simulationInput, signals] = create_phase2b_simulation_input( ...
        modelName, params, scenario)
%CREATE_PHASE2B_SIMULATION_INPUT Package one reproducible Simulink run.

arguments
    modelName (1,1) string
    params (1,1) struct
    scenario (1,1) struct
end

signals = phase2b_simulink_signals(params, scenario);
simulationInput = Simulink.SimulationInput(char(modelName));
simulationInput = simulationInput.setVariable( ...
    'phase2bEquivalentEncoderError', ...
    signals.phase2bEquivalentEncoderError);
simulationInput = simulationInput.setVariable( ...
    'phase2bAcceptedDelay', signals.phase2bAcceptedDelay);
simulationInput = simulationInput.setVariable( ...
    'phase2bSampleReceived', signals.phase2bSampleReceived);
simulationInput = simulationInput.setVariable( ...
    'phase2bDiagnostics', signals.phase2bDiagnostics);
simulationInput = simulationInput.setVariable( ...
    'phase2bScenario', scenario);
simulationInput = simulationInput.setVariable( ...
    'phase2bParameters', params);
simulationInput = simulationInput.setModelParameter( ...
    'StopTime', num2str(params.simulation.stopTime_s, 17));
end
