function [values,names]=phase3_logged_values(sample)
%PHASE3_LOGGED_VALUES Stable numeric interface; command is channel1.
names={'command_V','reference_rad','sensorMeasurement_rad','receivedMeasurement_rad', ...
 'estimatedPosition_rad','estimatedVelocity_rad_s','estimatedCurrent_A','innovation_rad', ...
 'mode','alarm','measurementAccepted','credibleFresh','estimateUsable','predictionAge_s', ...
 'commandLimit_V','unsaturatedCommand_V','sourceIndex','sampleReceived','resetRequest','supplyHealthy', ...
 'referencePosition_rad','referenceSourceIndex','referenceReceived','reacquisitionRequest', ...
 'reacquisitionQualified','reacquisitionCommitted','reacquisitionPositionBound_rad', ...
 'reacquisitionVelocityBound_rad_s','reacquisitionCurrentBound_A', ...
 'reacquisitionFitResidual_rad','referenceUncertainty_rad'};
values=zeros(1,numel(names));
if nargin>0,for j=1:numel(names),values(j)=double(sample.(names{j}));end,end
end
