function design=phase3_stop_hold_configuration()
%PHASE3_STOP_HOLD_CONFIGURATION Frozen standalone passive-brake study.
% Engineering assumptions only. No controller, observer, or model promotion.
p=actuator_parameters();
design.id="PHASE3-STOP-HOLD-V1.0";
design.params=struct('R_ohm',p.electrical.resistance_Ohm, ...
 'L_H',p.electrical.inductance_H,'Kt_Nm_A',p.motor.torqueConstant_Nm_A, ...
 'Ke_V_s_rad',p.motor.backEmfConstant_V_s_rad,'J_kg_m2',p.mechanical.inertia_kg_m2, ...
 'b_Nm_s_rad',p.mechanical.viscousDamping_Nm_s_rad);
design.steps_s=[1e-4 5e-5 2.5e-5];design.exportInterval_s=.001;
design.mechanisms=struct('id',{'terminal_short','resistor','mechanical'}, ...
 'externalResistance_Ohm',{0,1.2,0},'capacity_Nm',{0,0,.030});
design.nominalEngagementDelay_s=.030;design.capacityRamp_s=.020;
design.gates=struct('energyClosure_J',1e-10,'finePositionError_rad',deg2rad(.05), ...
 'fineVelocityError_rad_s',.02,'fineCurrentError_A',.005, ...
 'fineNumericalLossFraction',.02,'energyScaleFloor_J',1e-8, ...
 'holdingVelocity_rad_s',1e-10,'holdingTail_s',.1,'holdingDrift_rad',1e-10);
design.assumptions="Reciprocal SI DC equivalent; constant linear R/L/Kt/Ke/J/b; ideal isolated short or series-resistor circuit; equal static/sliding Coulomb capacity; normally-applied brake represented by timed capacity, not a selected component; no backlash, wear, temperature, gearing, release interlock or observer integration";
design.integration="Backward Euler bounded friction inclusion; load sampled at interval midpoint with knots aligned to every grid; capacity sampled at right endpoint; discrete numerical dissipation reported separately; 1 ms trace export";
design.acceptance="Numerical correctness and bounded holding within declared capacity; overload, missing engagement and release are expected motion diagnostics, not hardware success; independent continuous hybrid audit required";
end
