function [measurement_rad,sensor_rad,sourceIndex,sampleReceived]=phase3_external_measurement(packet,currentIndex,heldMeasurement_rad)
%PHASE3_EXTERNAL_MEASUREMENT Strict decoded-position transport boundary.
% packet has exactly these fields:
%   measurement_rad: finite real scalar decoded position in radians.
%   sourceIndex: integer acquisition index, in [1,currentIndex] on receipt;
%                [0,currentIndex] without receipt (0 means no source yet).
%   sampleReceived: scalar logical; false retains heldMeasurement_rad.
% Index 1 denotes t=0. At physical t=k*Ts, a fresh packet has sourceIndex=k+1.
% Threshold/decoder events at that time must be resolved by the caller first.
% The adapter never quantizes, repairs counts, or infers freshness from value.
% Causal but nonincreasing receipts reach the observer's existing rejection
% rule; this interface does not grant them credibility. No truth, fault,
% exposure, receiver-domain, or offline annotation fields are accepted.
id='EMIProject:InvalidExternalMeasurement';
assert(isstruct(packet)&&isscalar(packet),id,'External measurement must be a scalar packet struct.');
required={'measurement_rad';'sourceIndex';'sampleReceived'};
assert(isequal(sort(fieldnames(packet)),sort(required)),id, ...
 'Packet fields must be exactly measurement_rad, sourceIndex and sampleReceived.');
assert(isnumeric(currentIndex)&&isreal(currentIndex)&&isscalar(currentIndex)&& ...
 isfinite(currentIndex)&&currentIndex>=1&&currentIndex==fix(currentIndex),id, ...
 'Current sample index must be a positive integer.');
assert(isnumeric(heldMeasurement_rad)&&isreal(heldMeasurement_rad)&& ...
 isscalar(heldMeasurement_rad)&&isfinite(heldMeasurement_rad),id, ...
 'Held decoded measurement must be finite and real.');
assert(isnumeric(packet.measurement_rad)&&isreal(packet.measurement_rad)&& ...
 isscalar(packet.measurement_rad)&&isfinite(packet.measurement_rad),id, ...
 'Decoded measurement must be a finite real scalar.');
assert(islogical(packet.sampleReceived)&&isscalar(packet.sampleReceived),id, ...
 'sampleReceived must be a scalar logical.');
assert(isnumeric(packet.sourceIndex)&&isreal(packet.sourceIndex)&& ...
 isscalar(packet.sourceIndex)&&isfinite(packet.sourceIndex)&& ...
 packet.sourceIndex==fix(packet.sourceIndex)&&packet.sourceIndex>=0&& ...
 packet.sourceIndex<=currentIndex&& ...
 (~packet.sampleReceived||packet.sourceIndex>=1),id, ...
 'Source index must be causal and integer; received packets require a positive source index.');
sensor_rad=double(packet.measurement_rad);sourceIndex=double(packet.sourceIndex);
sampleReceived=packet.sampleReceived;measurement_rad=double(heldMeasurement_rad);
if sampleReceived,measurement_rad=sensor_rad;end
end
