function signals = phase2b_simulink_signals(params, scenario)
%PHASE2B_SIMULINK_SIGNALS Create sample-aligned inputs for Simulink.

arguments
    params (1,1) struct
    scenario (1,1) struct
end

validate_parameters(params);
sampleCount = round(params.simulation.stopTime_s / ...
    params.control.sampleTime_s) + 1;
time_s = (0:sampleCount-1)' .* params.control.sampleTime_s;
physical = physical_coupling_profile(time_s, params, scenario);
communication = communication_channel_profile(time_s, params, scenario);

diagnosticValues = [ ...
    physical.equivalentEncoderError_rad, ...
    physical.capacitiveCurrent_A, ...
    physical.capacitiveVoltage_V, ...
    physical.inductiveVoltage_V, ...
    physical.sharedImpedanceVoltage_V, ...
    physical.groundCommonModeVoltage_V, ...
    physical.groundDifferentialVoltage_V, ...
    physical.receiverDifferentialVoltage_V, ...
    double(physical.sourceWindowActive), ...
    double(physical.groundWindowActive), ...
    double(communication.channelEnabled), ...
    communication.transmitDelay_samples, ...
    double(communication.packetDropped), ...
    double(communication.sampleReceived), ...
    communication.acceptedSourceIndex, ...
    communication.acceptedDelay_samples, ...
    double(communication.heldLast), ...
    communication.measurementAge_samples, ...
    communication.collisionDiscardCount, ...
    communication.outOfOrderDiscardCount];

signals.time_s = time_s;
signals.physical = physical;
signals.communication = communication;
signals.phase2bEquivalentEncoderError = timeseries( ...
    physical.equivalentEncoderError_rad, time_s);
signals.phase2bAcceptedDelay = timeseries( ...
    communication.acceptedDelay_samples, time_s);
signals.phase2bSampleReceived = timeseries( ...
    double(communication.sampleReceived), time_s);
signals.phase2bDiagnostics = timeseries(diagnosticValues, time_s);
end
