function [summary, spectrum] = phase2a_windowed_spectrum(time_s, signal_rad, startTime_s, stopTime_s)
%PHASE2A_WINDOWED_SPECTRUM Explicit sampled-signal amplitude spectrum.
% Select [start,stop), remove its mean, apply periodic Hann weights, then
% compute an unpadded FFT. One-sided amplitudes use coherent-gain correction.
% Peak means the first largest non-DC bin, not an interpolated frequency.
id = 'EMIProject:InvalidSpectralInput';
assert(isnumeric(time_s) && isreal(time_s) && isvector(time_s) && ...
    isnumeric(signal_rad) && isreal(signal_rad) && isvector(signal_rad),id, ...
    'Time and signal must be real numeric vectors.');
t = double(time_s(:));x = double(signal_rad(:));
assert(numel(t)>=2 && numel(t)==numel(x) && all(isfinite(t)) && ...
    all(isfinite(x)) && all(diff(t)>0),id,'Records must be finite, equal-length and ordered.');
assert(isnumeric(startTime_s) && isreal(startTime_s) && isscalar(startTime_s) && isfinite(startTime_s) && ...
    isnumeric(stopTime_s) && isreal(stopTime_s) && isscalar(stopTime_s) && isfinite(stopTime_s) && ...
    stopTime_s>startTime_s,id,'A finite increasing active window is required.');
startTime_s=double(startTime_s);stopTime_s=double(stopTime_s);
Ts = median(diff(t));
Fs = 1/Ts;
assert(isfinite(Ts) && Ts>0 && isfinite(Fs) && Fs>0 && all(isfinite(diff(t))),id, ...
    'Sample time and rate must remain finite and representable.');
assert(all(abs(diff(t)-Ts)<=max(1e-12,64*eps(max(abs(t))))),id, ...
    'Spectrum requires a uniform sample grid; resampling is not performed.');
assert(startTime_s>=t(1) && stopTime_s<=t(end)+Ts+64*eps(max(abs(t))),id, ...
    'The requested active window must be covered by the sampled record.');
mask = t>=startTime_s & t<stopTime_s;
x = x(mask);selected = t(mask);N = numel(x);
assert(N>=8,id,'At least eight active samples are required.');
removedMean = mean(x);
centered = x-removedMean;
weights = 0.5-0.5*cos(2*pi*(0:N-1)'/N);
assert(isfinite(removedMean) && all(isfinite(centered)) && all(isfinite(weights)) && ...
    isfinite(N*Ts),id,'Spectral centering/window arithmetic exceeded finite range.');
transform = fft(centered.*weights,N);
assert(all(isfinite(transform)),id,'FFT arithmetic exceeded finite range.');
amplitude = abs(transform(1:floor(N/2)+1))/sum(weights);
if mod(N,2)==0
    amplitude(2:end-1) = 2*amplitude(2:end-1);
else
    amplitude(2:end) = 2*amplitude(2:end);
end
frequency_Hz = (0:floor(N/2))'*(Fs/N);
assert(all(isfinite(amplitude)) && all(isfinite(frequency_Hz)),id, ...
    'Spectral scaling exceeded finite range.');
spectrum = table(frequency_Hz,amplitude, ...
    'VariableNames',{'Frequency_Hz','OneSidedAmplitude_rad'});
hasAC = max(abs(centered))>64*eps(max(abs(x)));
peakFrequency = NaN;peakAmplitude = 0;peakBin = NaN;
if hasAC
    [peakAmplitude,index] = max(amplitude(2:end));
    peakBin = index; % Zero-based FFT bin; first non-DC bin is 1.
    peakFrequency = frequency_Hz(index+1);
end
summary = struct('RequestedStart_s',startTime_s,'RequestedStop_s',stopTime_s, ...
    'FirstSelectedTime_s',selected(1),'LastSelectedTime_s',selected(end), ...
    'SampleTime_s',Ts,'SampleRate_Hz',Fs,'ActiveSamples',N,'FFTLength',N, ...
    'RecordDuration_s',N*Ts,'FrequencyBinSpacing_Hz',Fs/N,'Nyquist_Hz',Fs/2, ...
    'Window',"periodic Hann",'CoherentGain',mean(weights), ...
    'MeanRemoved_rad',removedMean,'ZeroPadding',false,'DCExcludedFromPeak',true, ...
    'HasACSignal',hasAC,'PeakBin',peakBin,'PeakFrequency_Hz',peakFrequency, ...
    'PeakAmplitude_rad',peakAmplitude,'PeakRule',"first maximum non-DC FFT bin; no interpolation", ...
    'PeakInteriorBand',hasAC && peakFrequency>2*Fs/N && peakFrequency<Fs/2-2*Fs/N, ...
    'AmplitudeInterpretation',"Coherent-gain-corrected spectral ordinate, not a universal tone amplitude near DC/Nyquist or off-bin", ...
    'BoundaryInterpretation',"Peak interpretation requires an interior-band tone; equal maxima choose the first bin and near-ties can differ with roundoff", ...
    'AliasingScope',"Sampled encoder-error spectrum only; no anti-alias filter is modeled. Physical frequencies above Nyquist cannot be identified.");
end
