function result = simulate_phase2b_actuator(params, scenario)
%SIMULATE_PHASE2B_ACTUATOR Run the discrete actuator with Phase 2B faults.

arguments
    params (1,1) struct
    scenario (1,1) struct
end

validate_parameters(params);

Ts = params.control.sampleTime_s;
n = round(params.simulation.stopTime_s / Ts) + 1;
time_s = (0:n-1)' .* Ts;
reference_rad = zeros(n, 1);
reference_rad(time_s >= params.simulation.stepTime_s) = ...
    params.simulation.stepAmplitude_rad;
physical = physical_coupling_profile(time_s, params, scenario);
communication = communication_channel_profile(time_s, params, scenario);
supply = supply_fault_profile(time_s, params, scenario);

continuousPlant = actuator_state_space(params);
discretePlant = ss(c2d(continuousPlant, Ts, 'zoh'));
[plantA, plantB, plantC, plantD] = ssdata(discretePlant);

controller = design_baseline_controller(params, continuousPlant);
discreteController = ss(controller.discrete);
[controllerA, controllerB, controllerC, controllerD] = ...
    ssdata(discreteController);

plantState = zeros(size(plantA, 1), 1);
controllerState = zeros(size(controllerA, 1), 1);
previousDriveVoltage_V = 0;
lastReceivedMeasurement_rad = 0;

state = zeros(n, size(plantA, 1));
output = zeros(n, size(plantC, 1));
sensorSideMeasurement_rad = zeros(n, 1);
receivedMeasurement_rad = zeros(n, 1);
trackingError_rad = zeros(n, 1);
unsaturatedCommand_V = zeros(n, 1);
command_V = zeros(n, 1);
controllerState_log = zeros(n, size(controllerA, 1));

for k = 1:n
    y = plantC * plantState + ...
        plantD * [previousDriveVoltage_V; params.mechanical.nominalLoadTorque_Nm];
    state(k, :) = plantState.';
    output(k, :) = y.';

    sensorSideMeasurement_rad(k) = y(1) + ...
        physical.equivalentEncoderError_rad(k);

    if communication.sampleReceived(k)
        sourceIndex = communication.acceptedSourceIndex(k);
        lastReceivedMeasurement_rad = sensorSideMeasurement_rad(sourceIndex);
    end
    receivedMeasurement_rad(k) = lastReceivedMeasurement_rad;

    trackingError_rad(k) = reference_rad(k) - receivedMeasurement_rad(k);
    controllerState_log(k,:) = controllerState.';
    rawCommand = controllerC * controllerState + ...
        controllerD * trackingError_rad(k);
    unsaturatedCommand_V(k) = rawCommand;
    command_V(k) = min(max(unsaturatedCommand_V(k), ...
        -supply.commandLimit_V(k)), supply.commandLimit_V(k));

    if k < n
        if supply.driveAvailable(k)
            controllerState = controllerA * controllerState + ...
                controllerB * trackingError_rad(k);
        elseif supply.controllerStatePolicy == "reset"
            controllerState(:) = 0;
        end % "hold" retains x_k while the motor bus is unavailable.
        plantState = plantA * plantState + ...
            plantB * [command_V(k); params.mechanical.nominalLoadTorque_Nm];
        previousDriveVoltage_V = command_V(k);
    end
end

result.params = params;
result.scenario = scenario;
result.time_s = time_s;
result.reference_rad = reference_rad;
result.position_rad = output(:, 1);
result.velocity_rad_s = output(:, 2);
result.current_A = output(:, 3);
result.sensorSideMeasurement_rad = sensorSideMeasurement_rad;
result.receivedMeasurement_rad = receivedMeasurement_rad;
result.trackingError_rad = trackingError_rad;
result.unsaturatedCommand_V = unsaturatedCommand_V;
result.command_V = command_V;
result.state = state;
result.physical = physical;
result.communication = communication;
result.supply = supply;
result.controllerState_log = controllerState_log;
result.profile.configuredWindowActive = ...
    physical.configuredWindowActive | communication.configuredWindowActive | ...
    supply.configuredWindowActive;

result.timeSeries = table(time_s, reference_rad, result.position_rad, ...
    result.velocity_rad_s, result.current_A, ...
    sensorSideMeasurement_rad, receivedMeasurement_rad, ...
    trackingError_rad, command_V, unsaturatedCommand_V, ...
    physical.capacitiveCurrent_A, physical.capacitiveVoltage_V, ...
    physical.inductiveVoltage_V, physical.sharedImpedanceVoltage_V, ...
    physical.groundCommonModeVoltage_V, ...
    physical.groundDifferentialVoltage_V, ...
    physical.receiverDifferentialVoltage_V, ...
    physical.equivalentEncoderError_rad, ...
    physical.sourceWindowActive, physical.groundWindowActive, ...
    communication.channelEnabled, communication.transmitDelay_samples, ...
    communication.packetDropped, communication.sampleReceived, ...
    communication.acceptedSourceIndex, communication.acceptedDelay_samples, ...
    communication.heldLast, communication.measurementAge_samples, ...
    communication.measurementAge_s, communication.collisionDiscardCount, ...
    communication.outOfOrderDiscardCount, ...
    'VariableNames', { ...
    'time_s', 'reference_rad', 'position_rad', 'velocity_rad_s', 'current_A', ...
    'sensor_side_measurement_rad', 'received_measurement_rad', ...
    'tracking_error_rad', 'command_V', 'unsaturated_command_V', ...
    'capacitive_current_A', 'capacitive_voltage_V', ...
    'inductive_voltage_V', 'shared_impedance_voltage_V', ...
    'ground_common_mode_voltage_V', 'ground_differential_voltage_V', ...
    'receiver_differential_voltage_V', 'equivalent_encoder_error_rad', ...
    'physical_source_window_active', 'ground_window_active', ...
    'communication_channel_enabled', 'transmit_delay_samples', ...
    'packet_dropped', 'sample_received', 'accepted_source_index', ...
    'accepted_delay_samples', 'held_last', 'measurement_age_samples', ...
    'measurement_age_s', 'collision_discard_count', ...
    'out_of_order_discard_count'});
result.table = result.timeSeries;
% Supply diagnostics are separate to preserve the established Phase 2B CSV
% and 29-channel Simulink interface used by the exploratory study.
result.supplyTimeSeries = table(time_s, supply.voltage_V, supply.commandLimit_V, ...
    supply.driveAvailable, supply.configuredWindowActive, ...
    repmat(params.mechanical.nominalLoadTorque_Nm,n,1), ...
    'VariableNames', {'time_s','supply_voltage_V','command_limit_V', ...
    'drive_available','supply_window_active','load_torque_Nm'});
end
