function validate_phase3_observer_configuration(config, includeDerived)
%VALIDATE_PHASE3_OBSERVER_CONFIGURATION Reject invalid observer contracts.
arguments
    config (1,1) struct
    includeDerived (1,1) logical = true
end
id = 'EMIProject:InvalidObserverConfiguration';
positive = {'sampleTime_s','historyDuration_s','maxMeasurementAge_s', ...
    'maxPredictionTime_s','positionLimit_rad','rateLimit_rad_s','residualTrip_rad'};
for k=1:numel(positive)
    name=positive{k};
    assert(isfield(config,name) && localScalar(config.(name)) && config.(name)>0,id, ...
        'Observer %s must be a positive finite real scalar.',name);
end
assert(isfield(config,'residualClear_rad') && localScalar(config.residualClear_rad) && ...
    config.residualClear_rad>=0 && config.residualClear_rad<config.residualTrip_rad,id, ...
    'Residual clear threshold must be nonnegative and below the trip threshold.');
assert(config.historyDuration_s>=config.maxMeasurementAge_s && ...
    config.maxPredictionTime_s>=config.maxMeasurementAge_s,id, ...
    'History and maximum prediction time must cover the accepted measurement age.');
capacity=ceil(double(config.historyDuration_s)/double(config.sampleTime_s))+1;
assert(isfinite(capacity) && capacity>=2 && capacity<=1e6,id, ...
    'History capacity must be representable and at most one million samples.');
assert(isfield(config,'assumedLoadTorque_Nm') && localScalar(config.assumedLoadTorque_Nm),id, ...
    'Assumed load must be a finite real scalar.');
assert(isfield(config,'initialEstimate') && localArray(config.initialEstimate) && ...
    isvector(config.initialEstimate) && numel(config.initialEstimate)==3,id, ...
    'Initial estimate must have three finite real states.');
assert(isfield(config,'poleRates_rad_s') && localArray(config.poleRates_rad_s) && ...
    isvector(config.poleRates_rad_s) && numel(config.poleRates_rad_s)==3 && ...
    all(config.poleRates_rad_s>0) && numel(unique(config.poleRates_rad_s))==3,id, ...
    'Three distinct positive finite pole rates are required.');
assert(isfield(config,'A') && localArray(config.A) && isequal(size(config.A),[3,3]) && ...
    isfield(config,'B') && localArray(config.B) && isequal(size(config.B),[3,2]) && ...
    isfield(config,'C') && isequal(config.C,[1,0,0]),id,'Observer model must use three states and voltage/load inputs.');
if includeDerived
    assert(isfield(config,'correctionGain') && localArray(config.correctionGain) && ...
        isequal(size(config.correctionGain),[3,1]),id,'Correction gain must be finite and three by one.');
    assert(isfield(config,'targetDiscretePoles') && localArray(config.targetDiscretePoles) && ...
        numel(config.targetDiscretePoles)==3 && all(config.targetDiscretePoles>0 & config.targetDiscretePoles<1),id, ...
        'Discrete poles must be finite and strictly inside the unit circle.');
    requested=exp(-double(config.poleRates_rad_s(:))*double(config.sampleTime_s));
    assert(max(abs(sort(config.targetDiscretePoles(:))-sort(requested)))<=1e-12 && ...
        max(abs(sort(eig((eye(3)-config.correctionGain*config.C)*config.A))-sort(requested)))<=1e-7,id, ...
        'Correction gain, target poles and requested rates must agree.');
    assert(isfield(config,'historyCapacity') && localScalar(config.historyCapacity) && ...
        config.historyCapacity==capacity,id,'History capacity must match the declared duration and sample time.');
end
end

function valid=localScalar(value)
valid=isnumeric(value) && isreal(value) && isscalar(value) && isfinite(value);
end

function valid=localArray(value)
valid=isnumeric(value) && isreal(value) && all(isfinite(value),'all');
end
