function validate_parameters(params)
%VALIDATE_PARAMETERS Reject malformed inputs before arithmetic or simulation.
% Each value is checked before concatenation to prevent vector/text coercion.
positivePaths = ["electrical.nominalVoltage_V", "electrical.resistance_Ohm", ...
    "electrical.inductance_H", "motor.torqueConstant_Nm_A", ...
    "motor.backEmfConstant_V_s_rad", "mechanical.inertia_kg_m2", ...
    "mechanical.viscousDamping_Nm_s_rad", "sensor.encoderCountsPerRevolution", ...
    "control.sampleTime_s", "control.targetBandwidth_rad_s", ...
    "control.voltageLimit_V", "simulation.stopTime_s", ...
    "simulation.stepAmplitude_rad", "simulation.settlingBandFraction"];
values = localNumbers(params,positivePaths,'EMIProject:InvalidPositiveParameter');
localRequire(all(values > 0),'EMIProject:InvalidPositiveParameter', ...
    'Positive physical and simulation parameters must be greater than zero.');
step = localNumbers(params,"simulation.stepTime_s",'EMIProject:InvalidStepTime');
localRequire(step >= 0 && step < params.simulation.stopTime_s, ...
    'EMIProject:InvalidStepTime','Step time must lie in [0, stopTime).');
sampleIntervals = double(params.simulation.stopTime_s)/double(params.control.sampleTime_s);
localRequire(isfinite(sampleIntervals) && sampleIntervals >= 1 && ...
    sampleIntervals < flintmax && abs(sampleIntervals-round(sampleIntervals)) <= ...
    64*eps(max(1,abs(sampleIntervals))), ...
    'EMIProject:InvalidSimulationTimeGrid', ...
    'Stop time must be an integer number of controller sample intervals.');
localNumbers(params,"mechanical.nominalLoadTorque_Nm",'EMIProject:InvalidLoadTorque');
localRequire(params.simulation.settlingBandFraction < 1, ...
    'EMIProject:InvalidSettlingBand','The settling-band fraction must be less than one.');
localIntegers(params,"sensor.encoderCountsPerRevolution", ...
    'EMIProject:InvalidEncoderCount',1,flintmax);
localIntegers(params,["simulation.randomSeed","faults.encoder.gaussian.randomSeed"], ...
    'EMIProject:InvalidRandomSeed',0,2^32-1);
for group = ["gaussian","sinusoid","dropout"]
    localWindow(params,"faults.encoder."+group,params.simulation.stopTime_s, ...
        'EMIProject:InvalidFaultWindow');
end
jumpTime = localNumbers(params,"faults.encoder.countJump.time_s", ...
    'EMIProject:InvalidCountJumpTime');
localRequire(jumpTime >= 0 && jumpTime <= params.simulation.stopTime_s, ...
    'EMIProject:InvalidCountJumpTime','Count-jump time must lie within the simulation.');
faultValues = localNumbers(params,["faults.encoder.gaussian.standardDeviation_rad", ...
    "faults.encoder.sinusoid.amplitude_rad","faults.encoder.sinusoid.frequency_Hz"], ...
    'EMIProject:InvalidFaultMagnitude');
localRequire(all(faultValues >= 0),'EMIProject:InvalidFaultMagnitude', ...
    'Fault magnitudes and frequency must be nonnegative.');
localNumbers(params,"faults.encoder.sinusoid.phase_rad",'EMIProject:InvalidFaultPhase');
localIntegers(params,"faults.encoder.countJump.magnitude_counts", ...
    'EMIProject:InvalidCountJumpMagnitude',-flintmax,flintmax);
localTextChoice(params.faults.encoder.dropout.behavior,"hold-last", ...
    'EMIProject:UnsupportedDropoutBehavior');

positivePaths = ["source.switchingVoltageStep_V","source.pwmFrequency_Hz", ...
    "source.voltageRiseTime_s","source.voltageFallTime_s","source.currentStep_A", ...
    "source.currentRiseTime_s","source.observedBasebandFrequency_Hz", ...
    "receiver.differentialTermination_Ohm","receiver.differentialCapacitance_F", ...
    "receiver.bandwidth_Hz","receiver.differentialNoiseMargin_V", ...
    "receiver.commonModeLimit_V","receiver.minimumPulseWidth_s", ...
    "receiver.systemLevelEquivalentSensitivity_rad_V","metrics.recoveryThreshold_rad", ...
    "metrics.recoveryDwellSamples","metrics.crossValidationTolerance_rad"];
values = localNumbers(params,"phase2b."+positivePaths, ...
    'EMIProject:InvalidPhase2BPositiveParameter');
localRequire(all(values > 0),'EMIProject:InvalidPhase2BPositiveParameter', ...
    'Positive Phase 2B parameters must be greater than zero.');
nonnegativePaths = ["receiver.maxSpuriousCountsPerSample", ...
    "coupling.capacitive.linePositive_F","coupling.capacitive.lineNegative_F", ...
    "coupling.inductive.linePositive_H","coupling.inductive.lineNegative_H", ...
    "coupling.shared.returnResistance_Ohm","coupling.shared.returnInductance_H", ...
    "communication.fixedDelay_samples","communication.maximumJitter_samples", ...
    "communication.jitterRandomSeed","communication.packetLossRandomSeed"];
values = localNumbers(params,"phase2b."+nonnegativePaths, ...
    'EMIProject:InvalidPhase2BNonnegativeParameter');
localRequire(all(values >= 0),'EMIProject:InvalidPhase2BNonnegativeParameter', ...
    'Phase 2B magnitudes, delays and seeds must be nonnegative.');
localNumbers(params,"phase2b.groundOffset.voltage_V", ...
    'EMIProject:InvalidPhase2BNonnegativeParameter');
values = localNumbers(params,"phase2b."+["coupling.capacitive.pathTransferLinear", ...
    "coupling.inductive.pathTransferLinear","coupling.shared.commonModeToDifferential", ...
    "groundOffset.commonModeToDifferential"],'EMIProject:InvalidPhase2BAttenuation');
localRequire(all(values >= 0 & values <= 1),'EMIProject:InvalidPhase2BAttenuation', ...
    'Phase 2B transfer factors must lie between zero and one.');
for group = ["source","groundOffset","communication"]
    localWindow(params,"phase2b."+group,params.simulation.stopTime_s, ...
        'EMIProject:InvalidPhase2BWindow');
end
localRequire(params.phase2b.source.observedBasebandFrequency_Hz < ...
    0.5/params.control.sampleTime_s,'EMIProject:Phase2BFrequencyAboveNyquist', ...
    'The receiver-equivalent frequency must remain below Nyquist.');
probability = localNumbers(params,"phase2b.communication.packetLossProbability", ...
    'EMIProject:InvalidPacketLossProbability');
localRequire(probability >= 0 && probability <= 1,'EMIProject:InvalidPacketLossProbability', ...
    'Packet-loss probability must lie between zero and one.');
localIntegers(params,"phase2b."+["communication.fixedDelay_samples", ...
    "communication.maximumJitter_samples","receiver.maxSpuriousCountsPerSample"], ...
    'EMIProject:InvalidPhase2BIntegerParameter',0,flintmax);
localIntegers(params,"phase2b.metrics.recoveryDwellSamples", ...
    'EMIProject:InvalidPhase2BIntegerParameter',1,flintmax);
localIntegers(params,"phase2b."+["communication.jitterRandomSeed", ...
    "communication.packetLossRandomSeed"], ...
    'EMIProject:InvalidPhase2BIntegerParameter',0,2^32-1);
localTextChoice(params.phase2b.communication.lossBehavior,"hold-last", ...
    'EMIProject:UnsupportedCommunicationLossBehavior');

% Supply is optional for historical parameter structures.
if isfield(params,'supply')
    localWindow(params,"supply",params.simulation.stopTime_s,'EMIProject:InvalidSupplyWindow');
    voltage = localNumbers(params,["supply.sagVoltage_V","supply.interruptionVoltage_V"], ...
        'EMIProject:InvalidSupplyVoltage');
    localRequire(all(voltage >= 0 & voltage <= params.electrical.nominalVoltage_V), ...
        'EMIProject:InvalidSupplyVoltage','Supply fault voltages must lie between zero and nominal voltage.');
    localTextChoice(params.supply.controllerStatePolicy,["hold","reset"], ...
        'EMIProject:InvalidSupplyStatePolicy');
end
if params.control.sampleTime_s*params.control.targetBandwidth_rad_s > 0.1
    warning('EMIProject:LowSamplingRatio', ...
        'Controller sampling may be too slow relative to the target bandwidth.');
end
end

function values = localNumbers(params,paths,id)
values = zeros(size(paths));
for k = 1:numel(paths)
    value = params;
    parts = split(paths(k),'.');
    for j = 1:numel(parts)
        localRequire(isstruct(value) && isscalar(value) && isfield(value,parts(j)), ...
            id,'Required parameter structure or field is missing: %s.',paths(k));
        value = value.(parts(j));
    end
    localRequire(isnumeric(value) && isscalar(value) && isreal(value) && isfinite(value), ...
        id,'Parameter %s must be a finite real numeric scalar.',paths(k));
    values(k) = double(value);
end
end

function localIntegers(params,paths,id,low,high)
values = localNumbers(params,paths,id);
localRequire(all(values == fix(values) & values >= low & values <= high),id, ...
    'Count, delay and seed parameters must be integers within their supported range.');
end

function localWindow(params,path,stopTime,id)
values = localNumbers(params,[path+".startTime_s",path+".stopTime_s"],id);
localRequire(values(1) >= 0 && values(2) > values(1) && values(2) <= stopTime,id, ...
    'Each fault window must lie within the simulation and have positive duration.');
end

function localTextChoice(value,choices,id)
validText = (isstring(value) && isscalar(value) && ~ismissing(value)) || ...
    (ischar(value) && isrow(value));
localRequire(validText,id,'Behavior must be a supported scalar text value.');
localRequire(any(string(value) == choices),id,'Unsupported behavior or controller-state policy.');
end

function localRequire(condition,id,varargin)
if ~condition, error(id,varargin{:}); end
end
